### ISSUE TITLE
Hope to add the function of modifying the background color of the text

### ISSUE THREAD

**Issue by Moriarty1024** [brianpetro/obsidian-smart-connections#103]
Thanks for your plugin.

On my computer, the background color is as shown in the picture, and sometimes it is difficult to read certain texts because their color is the same as the background color.

![image](https://user-images.githubusercontent.com/37505758/227831409-c125ecc5-5ca7-4393-9e60-2778a2a166db.png)

**Comment by HurleyKane** [comment]
Hi@brianpetro 
I have a same problem with Building owner. my theme is Blue Topaz. but the background is blue. I can't adjust the background. I hope you help me.  blow is the illustration.
Thanks!
my friend
![image](https://user-images.githubusercontent.com/90821570/230896277-5d213f19-0753-4d7e-8121-170e0b6f7166.png)

**Comment by brianpetro** [comment]
@HurleyKane thanks for the screenshot. That makes this a lot easier for me to see what's going on.

I intend to make all the chat styles inherit the styles from the theme as I think this would be much better than simply overriding the theme and forcing a style.

However, I'm not very familiar with Obsidian themes. So I have been putting this off since it will require some learning curve.

If anyone wants to take a look, the chat styles start at this line https://github.com/brianpetro/obsidian-smart-connections/blob/d5d79d3f0abb5976740c2c62852928af8a2d070b/styles.css#L101

The necessary changes are static colors like https://github.com/brianpetro/obsidian-smart-connections/blob/d5d79d3f0abb5976740c2c62852928af8a2d070b/styles.css#L148

Which should be changes to variables set by the theme like https://github.com/brianpetro/obsidian-smart-connections/blob/d5d79d3f0abb5976740c2c62852928af8a2d070b/styles.css#L205

Thanks,
Brian 🌴

**Comment by Cody-W-Tucker** [comment]
This was my fix as a CSS snippet.
`.sc-message.assistant {
  background-color: var(--background-primary);
  color: var(--text-normal);
}`

**Comment by brianpetro** [comment]
The latest versions inherit the Obsidian theme 🌴

**Comment by brianpetro** [comment]
Recorded response https://youtu.be/OoYChPfdR5U
