### ISSUE TITLE
Turn off notification of retry

### ISSUE THREAD

**Issue by yshhwy** [brianpetro/obsidian-smart-connections#109]
If there exist failed files, whenever open a file, notification below would appear:
"Smart Connections: Skipping previously failed fle,use button in settings to retry"

I assume those files are too big to be submitted to AI Model. But being able to turn off the notification would be nice.

![](https://user-images.githubusercontent.com/80385343/227943039-b5c63971-581f-4363-ad7d-c0e7088f3a08.png)

**Comment by brianpetro** [comment]
@yshhwy Welcome to the Smart Connections community, and thanks for the feedback. 

Even big files should be able to be embedded (the exception is with some languages that use a different alphabet).

Have you tried the "retry failed embeddings" button in the settings? It might fix this if the errors were from something common, like rate limits.

However, if this is still a problem, let me know. I have been considering a way to "snooze" this alert. Or, at least, make it appear less often (maybe limit it to once every 10 minutes).

Thanks for your help in making Smart Connections better for everyone!
Brian🌴

**Comment by yshhwy** [comment]
Thank you for your patient response. Unfortunately, the problem still exists after several retries. Is there a method by which I can skip those files that have failed or "snooze" the alert?

**Comment by HenMie** [comment]
@brianpetro I have encountered the same problem where some files cannot be processed successfully even after multiple attempts. I can provide the MD files where the problems occurred. If this issue cannot be resolved for the time being, maybe offering a button to 'turn off the alarm' is a good choice. Thank you!
![image.png](https://s2.loli.net/2023/03/29/bfmAsqDiGpnj3uN.png)
Markdown files：https://wwuv.lanzoue.com/icgJK0rfl4ad

**Comment by brianpetro** [comment]
Thanks for sharing the file that's causing the issue. 

Based on the size and language of the file, I believe the problem is that the estimated tokens is incorrect so Smart Connections keeps trying to embed the file even though it's too large. 

Since we recently added language settings, I should be able to adjust the token calculation based on that setting. 

Thanks again for providing the insight to help me better understand what's going on here, I hope to get to this soon,
Brian 🌴
