### ISSUE TITLE
Not populating links

### ISSUE THREAD

**Issue by arminta7** [brianpetro/obsidian-smart-connections#12]
Getting this in the logs

<img width="398" alt="Screenshot 2023-01-09 at 19 42 16" src="https://user-images.githubusercontent.com/7927356/211436362-3b80b9a3-01ff-48f4-b5d6-4269d3c3f306.png">

**Comment by brianpetro** [comment]
The loud/breaking part of that error is fixed by ensuring the downstream code can handle errors from the OpenAI API. 

However, that still doesn't explain why you're getting 400 errors in the first place, so I added the exact response from OpenAI to the console log when this occurs. This way, if you see 400 errors, we should also see a response object from OpenAI, which may give us more insight into what's happening.

**Comment by arminta7** [comment]
This was working again until the recent update 1.0.31 now I'm getting this:
<img width="387" alt="Screenshot 2023-01-10 at 16 11 47" src="https://user-images.githubusercontent.com/7927356/211663721-ba5f865f-4f5f-4cd7-8c3c-f3ccf7b56099.png">

**Comment by brianpetro** [comment]
Thanks for this!

`1.0.31` included developments that should decrease total token usage. But, I didn't want to require refreshing all embeddings right away, so embeddings start to use the improved storage strategy gradually. This bug was at the intersection of those two strategies. 

And thanks for the always speedy updates! 😊

**Comment by brianpetro** [comment]
Oh, forgot to mention that `1.0.32` should've fixed the above issue, too.

**Comment by arminta7** [comment]
Still not working after the update. Looks like the same error.

**Comment by brianpetro** [comment]
I just added the last thing I could think of for the last error you screenshotted. 

PS- the screenshots are a real big help, thanks!

**Comment by arminta7** [comment]
Links are working now! 🎉

Still getting the 400 errors in the logs, which is fine as long as I can get rid of these popups (they happen every time I navigate to a new page) I can open a new issue for this if that's better. 

<img width="330" alt="Screenshot 2023-01-10 at 19 39 37" src="https://user-images.githubusercontent.com/7927356/211691629-abf1f728-913d-429c-a192-9f776c67c4ac.png">

Thanks for addressing everything so quickly!

**Comment by arminta7** [comment]
All better! Thank you!

**Comment by brianpetro** [comment]
OpenAI Error notification muted :)

But I'm stumped about what to do with those 400 errors. I think there might be a character encoding issue. I recently reduced the maximum character length per embedding, which would have at least reduced the number of these errors if input size was the issue (input greater than max tokens).

**Comment by brianpetro** [comment]
Moving discussion about 400 errors to https://github.com/brianpetro/obsidian-smart-connections/issues/10
