### ISSUE TITLE
Failed embedding batches - causing full reprocessing of embeddings?

### ISSUE THREAD

**Issue by schartkoff** [brianpetro/obsidian-smart-connections#123]
Something went screwy with the processing of embeddings in my vault. I'm getting failed embedding batch errors (see screenshot 1): ![image](https://user-images.githubusercontent.com/41761209/228633598-887421d6-02a2-41b0-a3a4-51beb45eea8f.png)

I'm not sure what's causing these. The real problem is that none of the status from successful files in these embedding batches seems to be retained, and my OpenAI account was getting hit with retry attempts every 5 minutes. This has run my account to the hard usage limit I set, and I've disabled the plugin until I get some advice on how to proceed.
![image](https://user-images.githubusercontent.com/41761209/228639889-a86922c8-e82a-4322-b218-7a0c89e35427.png)

I've double-checked that nothing else is touching these files to change the modified time.

Ideas?

**Comment by brianpetro** [comment]
@schartkoff welcome to the community and thanks for making this report.

Have you tried the retry failed embeddings button? This could have just been a rate limit issue, even with the paid account it still happens sometimes, especially during initial processing.

There are also two "render log" settings that you can enable for more clarity into which files are being processed. This will render information about which files are processed in the console log.

Let me know if that clears anything up or if you see anything else that might help us figure this out.

Thanks for the help,
Brian 🌴

**Comment by schartkoff** [comment]
Okay, I restarted Obsidian, upped my usage quota a bit, and retried failed embeddings. I now am showing no failed embeddings (great!), but for some reason, OpenAI is continuing to receive and process continuous requests:
![image](https://user-images.githubusercontent.com/41761209/228668080-757971df-61ec-457e-9a2f-77ee6d05d149.png)

The only developer console message for smart-connections (outside of loading all plugins) is "loading external embeddings".

When I look in the .smart-connections folder, I see the following files:
![image](https://user-images.githubusercontent.com/41761209/228672038-b0d394ad-ce35-4382-8703-bcecc1d12fb1.png)

I notice that none of these have today's date, even though embeddings processing has run today. Could that be a clue?

**Comment by brianpetro** [comment]
Toggle on both "render log" options in the settings.

Then, anytime the embeddings API is used, it will print exactly which files were embedded.

Make sure your updated to the most recent version. There was a saving bug a while back, but since yours saved at all, it's probably not that. A log should be printed to the console after each save. 

Let me know if that clears some things up. 

🌴

**Comment by schartkoff** [comment]
Okay, I've done all of that - fully updated, all logs turned on.
Here is the error that I'm seeing in the dev console now:
![image](https://user-images.githubusercontent.com/41761209/228936529-04cc41cb-c061-4104-a9ad-d6b46d6f1c48.png)

I don't see any logs that embeddings have been saved.

**Comment by brianpetro** [comment]
@schartkoff, congratulations on being the first to have such a large Obsidian vault that it breaks `JSON.stringify` 🤣

![Desktop-screenshot (3)](https://user-images.githubusercontent.com/1886014/228952493-aa93c4b9-27e7-4704-b67f-f9cb0795806e.png)

**Comment by brianpetro** [comment]
I'm working on a major update for Smart Chat right now. But I have been planning on a HNSW-esque update that would solve this. Can't give an ETA right now, but hopefully soon.

In the meantime, there are the exclusion settings you can use if you have any less important folders that could be excluded to reduce your total number of embeddings.

**Comment by brianpetro** [comment]
@schartkoff unfortunately, no, that won't work.

But, I did think of something!

There is a setting `skip_sections` that, depending on how your notes are formatted, may significantly reduce the total number of embeddings for your vault.

This setting limits embeddings to one-per-note when toggled on. 

Let me know if that works for you.

Brian🌴

**Comment by schartkoff** [comment]
Thanks for that -- I changed that setting, as well as corrected a bunch of more aggressive folder exclusions. It seemed to work okay at first and produced a somewhat smaller embeddings file, but now I'm getting new errors.

![2023-03-31 21_18_09](https://user-images.githubusercontent.com/41761209/229258916-3a854db5-0a01-4bda-a0a1-7b1a8ad4ab75.png)

I know the next things I'm going to say are FRs and won't necessarily be quick in coming even if you agree in concept, but:
1. would you consider adding a toggle to turn embedding updates on/off? At this point while working through issues, the only means I have to stop continuous retries that still run up token processing is to either delete the API key in the smart connections settings or disable the plugin. These approaches are (a) clunky; and (b) prevent me from viewing connections based on what has successfully processed.
2. would you consider adding some failsafe to automatically turn embedding updates off after one or X failed embedding batches or attempts to save embeddings? I want to love this plugin and give it a full fair shake, but I'm afraid of what's possible if I take my eye off the usage meter for any length of time.

Thanks for all your help so far!

**Comment by brianpetro** [comment]
@schartkoff thanks for the update! I'm happy to here that your making progress 😊

Re: FRs

1) Being able to work without continuous embedding, or pausing new embeddings, is on the roadmap. I plan on making an update for mobile soonish. And I think the mobile update might include something like this for the sake of reducing load on devices. 

2) You shouldn't be charged for failed requests. And files that fail aren't retried until you hit the manual retry button (unless the failure is because 429 rate limiting errors which will be retried 3 times before being added to the list). These API failures are better handled because of there relatively common compared to the previous error you encountered from the impressive size of your vault.

I hope that clears some things up. 

Lastly, if the same files keep failing with the 400 error, I'd be interested in seeing the file to figure out what might be tripping up the API. 

Thanks for your help in providing useful feedback about Smart Connections!

Brian 🌴

**Comment by brianpetro** [comment]
The embedding process has been significantly updated since this issue was last active. Please create a new issue if you encounter new problems in the future 🌴
