### ISSUE TITLE
FR - posibility to run using gpt4all

### ISSUE THREAD

**Issue by belizar** [brianpetro/obsidian-smart-connections#124]
Yesterday I found [this](https://twitter.com/andriy_mulyar/status/1640836003194630144?s=48). [Repo Link](https://github.com/nomic-ai/gpt4all). It allows the chance to run an LLM on a laptop.

Just because I do not want to send my Obsidian notes through the internet to a cloud-hosted LLM I like to link Smart Connections with a local model.

Thanks!

**Comment by brianpetro** [comment]
GPT4All looks like a huge step toward local models.

Smart Connections uses embeddings, too. So I'm looking forward to seeing similar local models developments for Embeddings models (important because this is the model that needs to access your whole vault, the generative model only sees the context used during chat sessions).

Then we can look forward to having two options in Smart Connections, 1) local models for privacy, and 2) SOTA cloud models for performance.

**Comment by brianpetro** [comment]
Relevant note https://github.com/brianpetro/obsidian-smart-connections/issues/137#issuecomment-1492775955

**Comment by brianpetro** [comment]
Also relevant https://github.com/brianpetro/obsidian-smart-connections/issues/117#issuecomment-1492570808

**Comment by brianpetro** [comment]
Recorded response https://youtu.be/RYAMhpV2uq4
