### ISSUE TITLE
FR Prevent "exceeding max tokens" error by recalculating after error (also a fix for languages with non-english alphabet)

### ISSUE THREAD

**Issue by brianpetro** [brianpetro/obsidian-smart-connections#126]
**Request for contributors**: I am eager to support all languages, but given the constraints on my time, I must prioritize. As this plugin is open-source, the optimal approach to include additional languages is by empowering others to contribute the necessary enhancements.

By concentrating on language-agnostic features, I believe I can provide the most value to this project and the broader community.

If you are interested in making this contribution, please review the notes below and leave a comment. I'll be happy to provide feedback and guidance.

Thanks for your support and contributions whether through helpful feedback, code, or something else!
Brian🌴

---
Current notes on this feature:

Using that same token estimation calculation, divide by 4, fails in some other languages. Adjust the token calculation based on the language setting. 

Without having to add an additional way to count tokens, we could implement a method to catch this error, and since the error contains the actual amount of tokens, use that amount in the error response to estimate the necessary size reduction of input sent to the API. 

ref https://github.com/brianpetro/obsidian-smart-connections/issues/109#issuecomment-1488725335

Causes this issue https://github.com/brianpetro/obsidian-smart-connections/issues/109#issuecomment-1488612574

And this https://github.com/brianpetro/obsidian-smart-connections/issues/51#issuecomment-1484102452

Another https://github.com/brianpetro/obsidian-smart-connections/issues/74#issuecomment-1478306700

**Comment by brianpetro** [comment]
ref https://github.com/brianpetro/obsidian-smart-connections/issues/109#issuecomment-1488612574

**Comment by BKDragon** [comment]
I am a Chinese user, and I initially encountered the problem of "Maximum context length is 4097 tokens".

I saw the issue and tried to fix it myself. I found this code snippet in main.js:

`  async get_context_for_prompt(nearest) {
    let context = [];
    const MAX_SOURCES = 5; // 10 * 1000 (max chars) = 10,000 chars (must be under ~16,000 chars or 4K tokens) 
    const MAX_CHARS = 800;
    let char_accum = 0;
`
I made some changes as prompted, and now the error "Maximum context length is 4097 tokens" has been resolved. But my the chatbot became silly.

I checked the log and found that this was due to the short context sent to GPT 3.5. But this has reached the current Token limit, in chinese.

According to OpenAI's official calculator, a Chinese character is basically equal to 2 tokens. 
On the other hand, a Chinese word generally needs 2 or 4 Chinese characters. 

This means that a Chinese word consumes about four times as much Tokens as an English word. 

If we send only one request per conversation, and if we restrict MAX_CHARS and MAX_SOURCES according to Chinese, it will result in too little valid information for API to return a wise answer.

We need to send the content to GPT multiple times and return a single result, for more languages like Chinese.

**Comment by brianpetro** [comment]
Without having to add an additional way to count tokens, we could implement a method to catch this error, and since the error contains the actual amount of tokens, use that amount in the error response to estimate the necessary size reduction of input sent to the API.

**Comment by brianpetro** [comment]
I'm closing this for now, but please reopen it if it is still an issue 🌴

**Comment by brianpetro** [comment]
Recorded response https://youtu.be/RYAMhpV2uq4
