### ISSUE TITLE
Updating my current embedded file for upcoming, more memory efficient versions of Smart Connections plug in

### ISSUE THREAD

**Issue by dvl00** [brianpetro/obsidian-smart-connections#160]
Hi @brianpetro,

I recently installed your plug in and ran it on my project. However, I noticed that the embedded file it created was very large and it cost me more than I expected (this is not the issue). I understand that you are working on a new version of your plug in that would allow creating multiple smaller embedded files instead of one big one. This would reduce the memory usage.

My question is, if I already have the large embedded file from the current version of your plug in, how can I split it into smaller ones so that it can work with the upcoming update of your plug in? I don't want to run the plug in again and incur the cost of creating a new embedded file from scratch. Just so you know, I uninstalled it from my computer as my memory would not be enough to run the plug in. 

Thank you for your advice and your great work on the plug in.

Sincerely,
@dvl00

**Comment by brianpetro** [comment]
@dvl00 When I make the update, I will be able to convert the previous file into the new format. I understand that cost can be prohibitive, so I try to make sure new embeddings are only created when necessary.

There is a possibility that you can use the plugin before that update, but I *you must* backup your `embeddings-2.json` file before doing the following:

There is a setting `skip_sections` that, depending on how your notes are formatted, may significantly reduce the total number of embeddings for your vault.

This setting limits embeddings to one-per-note when toggled on.

That setting may make the plugin usable prior to improving the handling of local embeddings.

Also, *I'd like to get your thoughts on this*: would you be willing to install a desktop application to manage your large amount of embeddings? 

It's something I've been considering because it would allow utilizing some additional tech that isn't possible within the plugin alone. 

I still plan on improving how the plugin handles the storage and memory, but the desktop app would likely allow the biggest performance gains. So it would be interesting to know if that would be something you're interested in. 

Thanks,
Brian 🌴

**Comment by dvl00** [comment]
Of course. I can try the desktop app and also the setting change. If you like, you can add me to linked in via this one time link to send me where to download the file and instructions if you don't want to make this public?

https://one-time.link/?esqc-RDg#SisF0Hn7FThEuEMt7XoXdUtjpPiK0eBHKkj8VGES7TjV


Also, I found this on twitter, I found the first comment specially relevant: 

https://twitter.com/virattt/status/1644329667673878528?t=tdvRL5p1qoXU5mXB6Tqk-g&s=19

Thank you for being so gracious with our feedback! You've probably already thought about all this stuff! 

Cheers

**Comment by brianpetro** [comment]
@dvl00 thanks for the follow-up!

After you back-up the `embeddings-2.json`, you may have to use the `force refresh` button so that the `skip_sections` setting takes effect. To confirm this, you can check if the `embeddings-2.json` has reduced in size since turning on the setting. If not, you will have to force refresh.

And good to know about the desktop app, thanks. I will reach out to you to for beta testing if I decide to go that direction.

Thanks
Brian 🌴

**Comment by dvl00** [comment]
Unfortunately, this option did not work. However, not to worry, I will wait until further notice! thank you!

**Comment by brianpetro** [comment]
Closing this for now since a lot has changed. If performance is still a concern please create a new issue to help clarify in terms of the latest updates 🌴

**Comment by brianpetro** [comment]
Recorded response https://youtu.be/VRslvjrcfnQ
