### ISSUE TITLE
FR: Setting to save embeddings.json to a specific location

### ISSUE THREAD

**Issue by brimwats** [brianpetro/obsidian-smart-connections#22]
I'd like to save the embeddings file to a specific folder to avoid syncing it

**Comment by brianpetro** [comment]
Which method are you using for syncing? 

In the meantime, there's an "Exclude folders" setting in the core "Sync" plugin.

![selective-sync](https://user-images.githubusercontent.com/1886014/213312334-c3e73f31-9e83-4105-a6a1-8b4d2e016cd9.png)

**Comment by brimwats** [comment]
syncthing, which also has exclusions. this request probably came from my need to organize everything before I realized I could just hide the embeddings folder. so hmm I guess if it's easy to implement others might like it but no need if it's harder!

**Comment by NightOwlCoder** [comment]
I actually need that, as I use iCloud sync.

**Comment by brianpetro** [comment]
@NightOwlCoder I'm not familiar with iCloud sync. Can you give me an idea of how to make this work for you?

Ex. Does the specified folder need to be outside of the vault? Or just a specific name?

Thanks!

**Comment by lukemt** [comment]
@brianpetro I can tell you: You need to change the folder name to `something.nosync`. In this case `.smart-connections.nosync` would make sense. Unfortunately this is the only way to prevent files from syncing with icloud. 

I think for every icloud user this would be good because it seems to somtimes stop icloud from syncing anything. Although I have no proof of that, just currently it's stuck and I think, this might be the issue.

An option to change the folder name or "add .nosync to the folder name for icloud users" would be great!

Thank you!

**Comment by brianpetro** [comment]
Hey @lukemt 

Thanks for explaining this as it will help me better prioritize this development.

Brian 🌴

**Comment by shepner** [comment]
I use git for my syncing process and would be much happier if the `.smart-connections` dir tree could be relocated into into `.obsidian/plugins/smart-connections` rather than cluttering up the root of my dir tree.  It would also be nice if the API key could be stored by itself in a separate file so it can be excluded.  Displaying the API key's file location in the UI would be a nice bonus.  Being able to manually specify a location completely outside of the vault would be ideal.

**Comment by ElanHasson** [comment]
Yes, and adding to `.gitignore` should be optional. Embeddings are expensive and I'd like them shared across my multiple machines.

**Comment by rlustemberg** [comment]
Indeed embeddings.json are not shared between instances of the plugin running on different computers. There's no way to exclude the directory from iCloud sync as we would have if we sync through git. I'll have a look at the code and see what I can do

**Comment by brianpetro** [comment]
@rlustemberg One of the challenges with the syncing is that the embedding file is often >100MB while it often changes by just a few KB at a time. This is the easiest storage solution, but it has its drawbacks, like, in this case, inefficiency in syncing.

My solutions for solving this involve changing how the embeddings are stored. For example, the main embeddings file may remain unchanged until some predefined time by creating additional files for new embeddings. This would reduce the main (large) file syncing to once per session while intermittently syncing a smaller file with recent changes. 

I have been embedding the notes on each device separately in my setup. Given the low cost of the embedding API, this hasn't been a problem cost-wise since only the changed notes are embedded on the additional devices after the initial processing.

If you have many notes, the initial processing will be what causes the most usage. In case you want to avoid that additional cost, I recommend manually copying the embedding file from the first device to subsequent devices. From then on, any cost for "double embedding" changes is almost negligible.

I appreciate you taking the time to look into this. Please let me know if I am missing anything!

Thanks
Brian 🌴

**Comment by lukemt** [comment]
I mean, if I could just rename `.smart-connections` to `.smart-connections.nosync` I'd be happy

**Comment by brianpetro** [comment]
![Screenshot 2024-06-27 091418](https://github.com/brianpetro/obsidian-smart-connections/assets/1886014/bc1dff9f-450e-40eb-825a-1d8212a047aa)

The Smart Connections folder can now be changed in the settings 🌴

**Comment by brianpetro** [comment]
Recorded response https://youtu.be/4Tlm-TfFHLY
