### ISSUE TITLE
Sidebar YAML /Dataview display issues

### ISSUE THREAD

**Issue by kuku652** [brianpetro/obsidian-smart-connections#231]
SC It's my favorite Obsidian plugin. Obsidian management/organizing game changer 
But I used a lot of YAML /Dataview. My SC`s Sidebar complete mess up by YAML and Dataview.

![Screenshot - 2023-06-02 12 56 21](https://github.com/brianpetro/obsidian-smart-connections/assets/57426272/067cd969-35a8-43a0-b242-5520d3d39865)

hope have the option to turn off the code(YAML , Dataview...) display.
or don`t display header_exclusions in Sidebar . 
（header_exclusions Will not be displayed separatel , but they displayed  in Sidebar  ，with  other Content. )

**Comment by Cody-W-Tucker** [comment]
I have this issue too, Frontmatter is an Obsidian native feature so it makes sense to solve. Would something simple like this work @brianpetro?

block_parser(markdown, file_path){
    // Add these lines at the start of the function to remove YAML front matter
    const frontMatterRegex = /^---[\s\S]*?---/;
    markdown = markdown.replace(frontMatterRegex, '');

    // ... rest of the function ...
}

https://github.com/brianpetro/obsidian-smart-connections/blob/4ca9bc944ae83e66b06b5b5d3b463609f74908e7/src/index.js#LL1040C3-L1117C1

**Comment by brianpetro** [comment]
As of a recent update, frontmatter should be parsed as a block. There is more I want to do with frontmatter in the future, like specifying properties that should be included in all blocks via the "breadcrumbs" context.

For an update on dataview:
- should be parsed when used in Smart Chat
- working on a frontmatter property that will parse dataview when embedding the currently active note that's used when getting Smart View results
- no plans to render dataview within the Smart View results due to performance issues
🌴

**Comment by brianpetro** [comment]
[Recorded response](https://youtu.be/J5sE5vFuQiU)
