### ISSUE TITLE
Do not have access to your notes?

### ISSUE THREAD

**Issue by naive231** [brianpetro/obsidian-smart-connections#240]
I get this error while asking some question in Chat window:

> 抱歉，我無法回答這個問題，因為我沒有訪問您的筆記的權限。請您自行查看您的筆記，或者提供更多上下文或詳細的問題描述，讓我能夠更好地回答您的問題。
(Sorry, I cannot answer this question because I do not have access to your notes. Please check your notes yourself or provide more context or a detailed description of the problem so that I can better answer your question.)

I don't know what permissions should be setting up?

**Comment by brianpetro** [comment]
@naive231 until more languages are supported by Smart Connections, you may need to use an English language self-referential pronoun in your message to trigger searching the notes (ex. "Based on *my* note*)

🌴

**Comment by Kmfernan5** [comment]
Each response from the qGPT will also contain links to the relevant notes that it used to answer your question. Click on one of those links in order to open that markdown file in your editor.[https://docs.pieces.app/extensions-plugins/obsidian#:~:text=Each%20response%20from%20the%20qGPT%20will%20also%20contain%20links%20to%20the%20relevant%20notes%20that%20it%20used%20to%20answer%20your%20question.%20Click%20on%20one%20of%20those%20links%20in%20order%20to%20open%20that%20markdown%20file%20in%20your%20editor.](url)
