### ISSUE TITLE
Smart Connections appears to have failed to process almost all the files within a folder

### ISSUE THREAD

**Issue by gw666** [brianpetro/obsidian-smart-connections#26]
The "Previously failed files" list is *very* large (well over 100 files in a vault that contains almost 600 files). Excluding a few miscellaneous files, all of the failed files are in the same folder (Zettelkasten). These comprise almost the entirety of the Zettelkasten folder. All files are .md files.

I got the above result even after doing a Force Refresh. File is attached below.

[GW-thinking-box ARCHIVE 1:21:23.zip](https://github.com/brianpetro/obsidian-smart-connections/files/10475731/GW-thinking-box.ARCHIVE.1.21.23.zip)

**Comment by brianpetro** [comment]
Are you using a paid OpenAI account?

If not, the rate limit is very low, like 20 notes max per minute, and because I haven't accounted for this, you will have to repeatedly retry the failed files until they all manage to complete. [This issue](https://github.com/brianpetro/obsidian-smart-connections/issues/24#issuecomment-1398419521) has more information. 

Attached is my embeddings file for your vault. You can try moving it into your smart-connections folder, and should save you from having to run those embeddings. 

[embeddings-2.zip](https://github.com/brianpetro/obsidian-smart-connections/files/10475916/embeddings-2.zip)

**Comment by gw666** [comment]
Thanks for the help. You can close this issue!
