### ISSUE TITLE
Implemented local models

### ISSUE THREAD

**Issue by ces3001** [brianpetro/obsidian-smart-connections#276]
I’m wondering if your platform-agnostic development has gotten anywhere with a locally run Llama or other open-source AI project that doesn’t require sending note data to a 3rd party?

Myself, and I assume many others, would prefer to have their vault content remain 100% private. The process of determining which notes have confidential material and which don’t in a vault that has 6K+ notes spanning 20+ years feels like a barrier too high for entry for me. Besides, *all* the notes have some level of personal identity in them, especially in aggregate, since I collected or wrote them all. 

Your plug-in would be especially useful for this type of massive vault.

**Comment by brianpetro** [comment]
When I say platform-agnostic, I really mean model-agnostic, so that would include local models.

However***

I 100% see the value of having options for local models. At this time, I have yet to become aware of any local models that would be both sufficiently effective and sufficiently easy to utilize by the average user of Smart Connections.

That said, I have been working on a desktop version Smart Connections, one that is much more feature-rich, and that I've been using myself for months. Unlike an Obsidian plugin, the desktop medium provides many more options for bundling local models in a way that would be accessible to average users, which is my target audience since more technically sophisticated users already have many other options available.

I hope that helps with better understanding my direction for this. I'd be happy to clarify anything you might still have questions about.

Thanks for your interest in Smart Connections 😊

Brian 🌴

**Comment by ces3001** [comment]
I would love to know more about your desktop version. Does it rely on OpenAI or is it completely self-contained? Are you looking for beta-testers? CecilOn Jul 3, 2023, at 4:40 AM, WFH Brian ***@***.***> wrote:﻿
When I say platform-agnostic, I really mean model-agnostic, so that would include local models.
However***
I 100% see the value of having options for local models. At this time, I have yet to become aware of any local models that would be both sufficiently effective and sufficiently easy to utilize by the average user of Smart Connections.
That said, I have been working on a desktop version Smart Connections, one that is much more feature-rich, and that I've been using myself for months. Unlike an Obsidian plugin, the desktop medium provides many more options for bundling local models in a way that would be accessible to average users, which is my target audience since more technically sophisticated users already have many other options available.
I hope that helps with better understanding my direction for this. I'd be happy to clarify anything you might still have questions about.
Thanks for your interest in Smart Connections 😊
Brian 🌴

**Comment by brianpetro** [comment]
The desktop app is currently my playground for all the experiment features I'm working on. My plan is to release the desktop app as a premium version of Smart Connections for enthusiasts that want to have the most control over the AI that enhances their personal PKM & productivity system.

I occasionally post demo videos on my Twitter https://twitter.com/wfhbrian

I don't have a timeline for local models because it depends on their open-source development. Fortunately, that development has been progressing quickly so I hope to have a better idea on that soon.

The Smart Connections ChatGPT plugin is a small subset of features from the desktop app and I'll be adding more features there before releasing the desktop app itself.

When I do release the premium desktop app, I plan to work closely with the initial users, and the best way to stay informed about that is following me on Twitter. 

Depending on the interest, I may also start a wait-list at https://SmartConnections.app

Thanks for your interest in Smart Connections,
Brian 🌴

**Comment by benp-mns** [comment]
Would something like this be useful here? https://github.com/go-skynet/LocalAI

OpenAI-compatible API and supports embeddings.

**Comment by brianpetro** [comment]
@benp-mns yes, thanks for sharing! I will have to look into this further.

**Comment by chymian** [comment]
+1 to support that fundamental request of being able to use local APIs like localAI, or https://github.com/Significant-Gravitas/Auto-GPT. it's basically a must, since I would never give my data away.
in that context, it would be nice if we could use already available local vectorDBs as well.

**Comment by brianpetro** [comment]
@chymian local APIs, very much on the roadmap. Right now it isn't possible without installing another desktop application. I have a project where I this "local model desktop app" will likely be coming soon. My intention is to fork that into something we can use for Smart Connections 🤓

Re: Auto-GPT request: the project you specifically are referring to is a generic implementation of "agent" type capabilities. Months ago I had developed an agent that works specifically with Obsidian, for example creating and editing notes. I do plan to merge those developments with Smart Connections. For additional agent capabilities, like web browsing, I think it currently makes most sense to rely on something like ChatGPT plugins, which effectively provide a type of agent implementation. Smart Connections supporters currently have access to a Smart Connections ChatGPT plugin, which allows making a request and ChatGPT interacting with both your notes and the other plugins you have enabled. Create/edit capabilities are currently unavailable in the ChatGPT plugin, but those are something I intend to implement.

Re: other vector DBs: this is unlikely due to requiring users to install third-party software, plus I'm pretty adamant that the requirements of personal vector storage do not require such software, of which nearly all are designed with the enterprise customer in mind.

Re: fediverse mastodon: I wouldn't say that I do a great job communicating things on Twitter, either. But my current "stealth" project may make increasing useful communications easier for me, across the board. So I'll keep that in mind. 

Thanks for your interest in helping make Smart Connections the best it can be 😊

🌴 Brian

**Comment by chymian** [comment]
@brianpetro thanks for the quick and promising reply.

>  I have a project where I this "local model desktop app" will likely be coming soon. My intention is to fork that into something we can use for Smart Connections

I'm curiously waiting for that app. :)

**Comment by mohamedaliznidi** [comment]
Hello, I was wondering if there are any updates regarding the feature request for localAI integration?

**Comment by brianpetro** [comment]
@mohamedaliznidi a local embedding model is the default in version 2.0 (now in early release for supporters).

Configurable chat models will come in v2.1 (unreleased, ETA currently not public). This will allow people with their own local chat models to access them via `localhost`, but as it currently stands, Smart Connections won't ship with a local chat model in 2.1, but will ship with additional API model options.

Hope that helps!

🌴

**Comment by mmgj** [comment]
Hi! 👋 Very excited about this project! Just to make sure I'm understanding everything correctly: Is it possible today, by paying or otherwise, to use this plugin without sending any of my notes data out? The "Become a supporter"-option in the settings suggests so, but isn't super clear about it.

**Comment by brianpetro** [comment]
Video Response -> https://youtu.be/sR7axWHQXV4
