### ISSUE TITLE
Error getting embeddings for files 

### ISSUE THREAD

**Issue by khoip1311** [brianpetro/obsidian-smart-connections#289]
I want to ask if any people encounter this problem. Many of my files couldn't get embeddings (especially recent ones); It always shows: "Error getting embeddings for:...".

I tried to retry failed files in the settings and make new API keys, but they didn't work.
Any solutions? Thanks!

**Comment by ahamedzoha** [comment]
Same issue here on my end as well. 
Additionally, the test API button **with** a valid API key often returns an error message.

**Comment by brianpetro** [comment]
> Additionally, the test API button with a valid API key often returns an error message.

@ahamedzoha if the test API key fails then something is wrong with your API key or account. 

🌴

**Comment by brianpetro** [comment]
@khoip1311 check the developer console log for errors.

If you're getting error code 429, then you probably need to setup billing in your OpenAI API account.

**Comment by khoip1311** [comment]
I think my errors may come from my API keys. If after I set up billing in my account and it worked, will it charge my money if I keep using it? 

<img width="826" alt="Screen Shot 2023-07-17 at 2 00 30 PM" src="https://github.com/brianpetro/obsidian-smart-connections/assets/139251265/1896fbd5-f2ae-4dd2-aaf6-655b3d7468d8">

**Comment by khoip1311** [comment]
> 

oh yes, I encounter the same as I test

**Comment by dapaning** [comment]
me too

**Comment by MichelleGDyason** [comment]
hi, i'm encountering an Error getting embeddings for: my current note. i'm unsure how to fix the issue. i have only just installed the plug-in and am very much looking forward to using it. Do you have any solutions to this issue? thanks

**Comment by annekaelber** [comment]
I just installed the plugin today. I set up my API key and filled in the appropriate Smart Connections fields. I even put a payment method (and limits!) in at OpenAI, just in case that was the issue. I'm still getting `"Error getting embeddings for:"` -- over many files. The "failed-embeddings file has 1500 documents listed.

I turned on the log_render and log_render_files options but I don't know where the "console" is to open it. (I turned them on because "log" seemed like a debugging setting...)

**Comment by brianpetro** [comment]
@annekaelber now that it's been some time since adding payment to your OpenAI API account, use the "retry failed files" button and see what happens. Sometimes it takes a few hours before the account rate-limits are increased.

If you're still having issues after that, the developer console can be opened using `CTRL+SHIFT+I` and may provide us with some error messages that we can use to figure things out.

Brian 🌴
