### ISSUE TITLE
FR: Vault querries

### ISSUE THREAD

**Issue by vguillet** [brianpetro/obsidian-smart-connections#29]
Love the plugin so far. I was wondering, since the plugin is already generating embeds for the entire vault, could it be possible to add a chat_gpt like query tool, with the goal of synthesising an answer from the vault's embedding along with the preexisting training data?

**Comment by brianpetro** [comment]
Yes!

**Comment by brianpetro** [comment]
Added search feature in `1.1.13`

The next step is to integrate it with GPT-3 to respond like ChatGPT would as if it had access to your notes.

Let me know what you think.

**Comment by brianpetro** [comment]
Added search feature in `1.1.13`

The next step is to integrate it with GPT-3 to respond like ChatGPT would as if it had access to your notes.

Let me know what you think.

![search-feature](https://user-images.githubusercontent.com/1886014/217377896-260a74e1-2a83-469e-b1eb-84f3e4f46626.png)

**Comment by brianpetro** [comment]
It. Is. Here. `v1.3.0`.

![smart-connections-chatgpt](https://user-images.githubusercontent.com/1886014/225181014-7c4bf596-3578-499c-88ea-9dc1c153052b.gif)

**Comment by brianpetro** [comment]
![smart-connections-chat-2](https://user-images.githubusercontent.com/1886014/225183261-770fbb4c-8cd0-49d0-96a2-634a0fdc2d18.gif)
![smart-connections-chat-3](https://user-images.githubusercontent.com/1886014/225183362-5a5bb5f5-3e67-43df-8452-b8289cdbb66d.gif)

**Comment by brianpetro** [comment]
![smart-connections-chat-5](https://user-images.githubusercontent.com/1886014/225183963-c235980a-fa92-40a7-a152-31c1a5051338.gif)
![smart-connections-chat-4](https://user-images.githubusercontent.com/1886014/225183966-78dba741-7f3d-447c-8bad-e13d6b069092.gif)

**Comment by brianpetro** [comment]
Currently, to trigger a search of your notes, you must use a self-referential pronoun like:

- I
- me
- my
- mine
- we
- us
- our
- ours

In the future, this will be configurable to be "Always on" and to include custom words that trigger ChatGPT to utilize the context of your notes.

**Comment by smartguy1196** [comment]
Nice work @brianpetro! This is amazing work! If I were you I would share this on Reddit and the Obsidian Forum. This is amazing!

**Comment by smartguy1196** [comment]
I can't believe it. We've reached the age where my school notes _can literally talk to me_

**Comment by vguillet** [comment]
This is awesome! Thank you for this great work!

**Comment by arminta7** [comment]
The results I am getting are not very accurate and I'm pretty sure it's because they're being funneled through hyd first. The most similar notes are correct in the normal list, but the notes being returned for the purpose of constructing the chat prompt are not. Is there a way to bypass hyd? 

For example if I ask something like "Based on my notes, what are the 8 Spheres of Existence?", it says it doesn't know, even though I have a note titled exactly that which details the definition. And when I look at which notes it was using for reference, the 8 Spheres of Existence note is not one of them.

**Comment by brianpetro** [comment]
Hey @arminta7 , thanks for checking out this new feature and providing feedback.

There are a lot of custom configurations possible. My possible features list is already filled with a bunch of them.

Given your example, since you already know exactly what you're looking for, have you considered simply going to that note and summarizing it?

For a general audience, HyDE will typically provide the best outcomes. However, there are some situations, like "answer based on this specific note," where it isn't necessary. That said, I plan on introducing a toggle to choose the chat context, ex. "Current Note" vs. "Full Vault," where the former would bypass HyDE.

Another thought, depending on the format of your notes, the issue may not be HyDE but that too many notes are being used. All of your relevant information may exist in only one of the ten notes included in the context provided to the AI. The ten number is somewhat arbitrary, but I plan to make it so that it starts with a smaller number and increases until the necessary information is found. This would significantly improve performance when all the necessary information is in one or just a few notes.

Thanks again for your insights!

**Comment by franciscoabenza** [comment]
We are missing a bit of info on how is implemented and tips to get the best out of the new feature. Is it only 10 notes?

![Screenshot 2023-03-16 at 12 24 10](https://user-images.githubusercontent.com/22050375/225605950-00d88d1d-b75d-4427-b7ec-57e05c6532ee.png)


> Currently, to trigger a search of your notes, you must use a self-referential pronoun like:
> 
> * I
> * me
> * my
> * mine
> * we
> * us
> * our
> * ours
> 
> In the future, this will be configurable to be "Always on" and to include custom words that trigger ChatGPT to utilize the context of your notes.

This for example should be explain on the [feature release ](https://wfhbrian.com/introducing-smart-chat-transform-your-obsidian-notes-into-interactive-ai-powered-conversations/)

**Comment by brianpetro** [comment]
@franciscoabenza, great insights, thanks! I already updated [the post](https://wfhbrian.com/introducing-smart-chat-transform-your-obsidian-notes-into-interactive-ai-powered-conversations/?cache=111#:~:text=Smart%20Chat%20feature.-,Using%20Smart%20Chat,-To%20access%20Smart).

Regarding the 10 notes, it's somewhat arbitrary, but I plan on improving how that number is selected with continued feedback from the community. It should be a dynamic number. It could be as low as one or much more than 100. It could be configurable. There are also some presets that would be more user-friendly that would adjust that number behind the scenes.

And thanks for the screenshot. Interesting that it didn't answer "Who am I?" for you. The second question wouldn't have triggered a context lookup. That matters because the context isn't stored in the chat history. And the last question, since it included one of the self-referential pronouns, did include the context.

I hope that answers some questions for you. And thanks for the help!
