### ISSUE TITLE
GPT4 plugin op open.ai?

### ISSUE THREAD

**Issue by ingewertwijn** [brianpetro/obsidian-smart-connections#295]
On Open AI, it is possible to connect with plugins. I see smart connections there, but it asks for an email and license key?

**Comment by brianpetro** [comment]
Hi @ingewertwijn 

That's correct. Because the ChatGPT plugin requires server hosting, it is currently reserved for Smart Connections' supporters. 

You can learn more about becoming a supporter at https://github.com/brianpetro/obsidian-smart-connections/discussions/285#discussioncomment-6426487

And the link to become a supporter is available in the settings of the Smart Connections Obsidian plugin. 

Thanks for your interest,
Brian 🌴

**Comment by ingewertwijn** [comment]
Hi Brian,

Thx for the info. You are not so clear on what money you need a supporter to contribute. Can you tell me?

Best regards,

Inge



This email has been written on a mobile device and may contain typos etc
________________________________

**Comment by brianpetro** [comment]
@ingewertwijn 

I'm still working out the details.

**Comment by mstrstvns** [comment]
Is that essentially a lifetime license?

**Comment by brianpetro** [comment]
@mstrstvns lifetime is a big promise. So let's assume the license is good for one-year.

I also expect a lot to change between now and the time the first licenses begin to expire, so I'll be reevaluating how we'll proceed in the future.

Thanks for your interest 
Brian 🌴
