### ISSUE TITLE
Part of UI is covered with toolbar

### ISSUE THREAD

**Issue by Yaski** [brianpetro/obsidian-smart-connections#296]
There is panel in below part of Obisidian window that covers Send button and input field

<img width="408" alt="image" src="https://github.com/brianpetro/obsidian-smart-connections/assets/1292529/b250697c-fbce-4b78-898a-690ca67c6231">

**Comment by RedLando** [comment]
Will this be addressed in a coming update?

**Comment by brianpetro** [comment]
@RedLando @Yaski 

That's a good question. While I can't say for sure because this is a more granular issue than what I'm currently focusing on. What I can say is that contributing code to fix an issue like this will be much easier. So even if it isn't address immediately in V2, the software architecture will be more amenable to contributions/updates that are necessary for solving issues like this.

I hope that makes sense and thanks for bringing this to my attention.

🌴

**Comment by RedLando** [comment]
> @RedLando @Yaski
> 
> That's a good question. While I can't say for sure because this is a more granular issue than what I'm currently focusing on. What I can say is that contributing code to fix an issue like this will be much easier. So even if it isn't address immediately in V2, the software architecture will be more amenable to contributions/updates that are necessary for solving issues like this.
> 
> I hope that makes sense and thanks for bringing this to my attention.
> 
> 🌴

@brianpetro Thank you for the prompt response. I am enjoying the work so far and looking forward to future features!

**Comment by brianpetro** [comment]
Should be fixed/improved in the latest versions 🌴😊
