### ISSUE TITLE
Too many requests when switching between notes

### ISSUE THREAD

**Issue by degregar** [brianpetro/obsidian-smart-connections#326]
Hi, I'm new and I find the plugin interesting. What I need is to occasionally semantically search for some notes, that I can't find otherwise, but the problem I have is that anytime I switch to a different note (like when I'm checking which one is the one I want to link to or read) and each time there is a request being sent to get embeddings for the note which hasn't changed in the meantime.

- How does the search bar works? Is it searching in all documents or only in those already found?
- Can we have a separate search by query modal, like in Semantic Search plugin?
- Can you prevent from sending embeddings for the note that already has embeddings fetched? Some cache mechanism?

I could help with that, but the `vec-lite` is missing.

**Comment by brianpetro** [comment]
Hi @degregar 

> How does the search bar works? Is it searching in all documents or only in those already found?

Searches all available 

> Can we have a separate search by query modal, like in Semantic Search plugin?

I'll have to see the model you're talking about, but probably yes. 

> Can you prevent from sending embeddings for the note that already has embeddings fetched? Some cache mechanism?

This is already happening. Basically, the note file size has to change by >10% to trigger re-embedding. 

However, based on your first paragraph, you might be confusing the "search for similar notes" calculation with re-embedding, because this "search for similar notes" does happen almost every time you open a note for the first time in a session (there is a per session cache).

I hope that helps clear things up,
🌴 Brian

**Comment by brianpetro** [comment]
Should be fixed/improved in the latest version 🌴
