### ISSUE TITLE
Fixed embedding failure when file size is too large 

### ISSUE THREAD

**Issue by paul2126** [brianpetro/obsidian-smart-connections#337]
It seems that when file size crosses 22KB the plugin fails to make embeddings. 

Is there workaround for this issue?

![image](https://github.com/brianpetro/obsidian-smart-connections/assets/29268973/0cbdfbd8-23d8-46fa-869e-dbe0946bf3a6)

**Comment by brianpetro** [comment]
Workaround: add some headings into the note.

Adding headings splits the note file into multiple embeddings. If there are no headings in the note, Smart Connections might try to embed the whole note and that may exceed the token limit which causes the 400 error. 

🌴 Brian

**Comment by paul2126** [comment]
Thank you for your reply. 

However, I still get embedding error even after dividing with the headings.
One difference was that the time it took for error to show up was longer. Before the heading, it showed after calculating up to 50 but now it calculates until 200 and shows the embeddings error.

Is there specific ways to input headings for it to work?

![image](https://github.com/brianpetro/obsidian-smart-connections/assets/29268973/5e02b9b8-c694-4cc5-af28-1efc02055f94)

**Comment by ReliablyAwkward** [comment]
Hello, I'm having a similar experience, although mine is something more akin to "Error getting embeddings + Error: New embeddings file size is significantly smaller than existing embeddings file size. A boarding to prevent possible loss of embedding data."

I have the log render selection enabled, but I don't seem to find where I can access it, is that what your screenshots are? If so, where are the sneaky little buggers hiding???

**Comment by paul2126** [comment]
@ReliablyAwkward you can access it through pressing `ctrl + shit + I` . And for me the workaround didn't help so I am just dividing the large files into smaller notes.

**Comment by ReliablyAwkward** [comment]
Ah, I see now...ok, thank you.....I wish the developer hosted something like a live Q&A once a week or something, Because I was so excited to use this plug-in for the longest time and finally sucked it up regarding putting my paranoia away about the openai privacy topic, and this is my third time now uninstalling and reinstalling the plug-in, Since it doesn't seem to work anywhere near like it's been advertised. 

I am hoping it's me so I can just make the adjustment and move on, but here is a screenshot of what happens after I started from scratch again, deleted all the embeddings, uninstalled and then reinstalled everything, the typical restart your computer crap, put the exclusions in first before putting in the API key, begin the embedding process and what you see in the screenshot I can't confirm what is happening.

What on earth is the darn-fangled problem!?? :(

![Console snapshot](https://github.com/brianpetro/obsidian-smart-connections/assets/135422842/62218f41-ae36-4a82-8c62-a52ccdca40d6)

![APi side](https://github.com/brianpetro/obsidian-smart-connections/assets/135422842/7984a4ce-b43d-4f76-8ab2-b7293c62552f)

**Comment by yan42685** [comment]
> Workaround: add some headings into the note.
> 
> Adding headings splits the note file into multiple embeddings. If there are no headings in the note, Smart Connections might try to embed the whole note and that may exceed the token limit which causes the 400 error.
> 
> 🌴 Brian

Hello, @brianpetro! I've encountered the same issue and can't solve the problem by adding headings to split notes with long content. I roughly read the process of generating embeddings for a single file, which is at the function `get_file_embeddings` (if I'm not wrong). Here is part of the code that is associated with `headings` and `embed_input` :
![image](https://github.com/brianpetro/obsidian-smart-connections/assets/41834091/30886332-cb0f-40dc-ad83-0cd629429d3f)
Based on my limited understanding of the code, when the length of the note content exceeds MAX_EMBED_STRING_LENGTH, this code does not generate multiple embeddings even if it encounters a heading. Instead, it only captures the content within the maximum length as file_embed_input. This approach seems to not address the issue of individual notes being too long and may result in the loss of information for content that exceeds the length limit.

**Comment by yan42685** [comment]
> Workaround: add some headings into the note.
> 
> Adding headings splits the note file into multiple embeddings. If there are no headings in the note, Smart Connections might try to embed the whole note and that may exceed the token limit which causes the 400 error.
> 
> 🌴 Brian

Hello, @brianpetro! I've encountered the same issue and can't solve the problem by adding headings to split notes with long content. I roughly read the procedure of generating embeddings for a single file, which is at the function `get_file_embeddings`. 

## Error Cause:
From my limited understanding, this function first calls `block_parser` to divide the file into multiple blocks based on headings. If there are multiple blocks, they are added to `block_embed_input`, and then the entire file's content is added to `file_embed_input`. The contents of these two "embed_inputs" are included in req_batch, which is then used as a parameter to call OpenAI's interface for generating embeddings.

The issue lies in the fact that although both `block_parser` and `get_file_embeddings` limit the text content to less than `MAX_EMBED_STRING_LENGTH == 25e3`, it does not ensure that the tokens consumed when sending the final request are less than 8191, which is the MAX INPUT TOKENS allowed for "model": "text-embedding-ada-002". Tests show that 15,000 'f' characters consume about 2,000 tokens, while 15,000 UTF-8 encoded characters '哈' consume about 15,000 tokens.

## Possible Solution:
Instead of using string length to limit the amount of text content, use OpenAI's tokenizer to verify the tokens about to be consumed. If it exceeds the limit, divide it into multiple requests, and have the multiple returned embeddings point to the same heading path.

Furthermore, if the file contains headings, it might be unnecessary to generate embeddings for the entire file, as embeddings at the heading level might express semantics more accurately (not sure if this is the case).

**Comment by brianpetro** [comment]
@yan42685 thanks for the analysis, and yes, you are correct about the possible solution.

I'm currently working on Smart Connections v2 and utilizing a tokenizer for more accurate calculations is in the planned development.

🌴
