### ISSUE TITLE
Fine-tuning with Embeddings

### ISSUE THREAD

**Issue by jprnd** [brianpetro/obsidian-smart-connections#34]
Can these embeddings be used for finetuning?
If so, what would that workflow look like with GPT-3?

Can I send these embeddings as prompts instead of large text?

**Comment by brianpetro** [comment]
Not for fine-tuning, but what you're looking for can still be achieved.

If you're like my clients, enabling GPT-3 to respond in the context of your data, in this case, your notes, then yes!

In short, the workflow looks like 1) using the embeddings to surface relevant notes, 2) merging the notes into a prompt, and 3) using GPT-3 to complete the prompt while instructing it to only answer in the context of the provided notes.

No, the embeddings can't be inputted into the prompts. And embeddings are over 15,000 characters each, even for just a single sentence, so you probably wouldn't want to even if you could.

However, Smart Connections generates more granular embeddings than just embedding the entire note. So you could include the most relevant paragraphs, sourced from multiple notes, in the prompt. You can see the granularity by using the plugin and viewing the results with expand/collapse button to show which "blocks" in the note were most relevant.

Combining GPT-3 with the embeddings isn't built-in into the plugin yet. But, since it can be done with different strategies for various use cases, I am working to make the API easily available to reuse these embeddings. So in addition to the GPT-3 querying strategy provided by default, it will be possible to use additional plugins that implement other strategies with the same embeddings.

This is a fun topic for me. So much so that I've written some blog posts. I think you would be interested in [alternatives to fine-tuning](https://wfhbrian.com/alternatives-to-fine-tuning/) and [an advanced strategy for surfacing embeddings](https://wfhbrian.com/revolutionizing-search-how-hypothetical-document-embeddings-hyde-can-save-time-and-increase-productivity/).

**Comment by jprnd** [comment]
Sweet! Thank you for those resources. I am looking into LangChain to "chat with my notes". 

It has an Obsidian loader: https://langchain.readthedocs.io/en/latest/modules/document_loaders/examples/obsidian.html
Chat Agents:
https://langchain.readthedocs.io/en/latest/use_cases/chatbots.html
and ways to integrate wolfram etc. 
https://langchain.readthedocs.io/en/latest/ecosystem/wolfram_alpha.html

**Comment by brianpetro** [comment]
@jprnd looks cool! 

LangChain is really popular.

Let me know how it goes.

**Comment by jasmeetchadha** [comment]
> 

I know nothing of how to implement this. But it is something I am looking to do too. How easy/difficult it is for a non-coder to do? 

Or can someone help me?

**Comment by brianpetro** [comment]
@jasmeetchadha I recommend checking out the OpenAI community forum and asking some questions about what you'd like to do there.

I'm closing this issue since it's not directly related to a bug or feature of Smart Connections.
