### ISSUE TITLE
 [Feature Request] Better Update Strategy for Embeddings

### ISSUE THREAD

**Issue by yan42685** [brianpetro/obsidian-smart-connections#374]
Upon reviewing the source code, I've noticed the conditions that trigger `get_all_embeddings` are:

- `retry_failed_files()`
- `force_refresh_embeddings_file()`
- `find_note_connections() && no nearest cache for this file`

However, for `get_all_embeddings` to actually initiate an embeddings update, `(curr.mtime != prev.mtime) && (delta_file_size / prev_file_size > 10%)` is required. Such an update strategy isn't fine-tuned enough:
- For larger files, a significant amount of text change is needed to trigger an update of the embeddings.
- If there are major edits, the actual content might change substantially, but the file size may not change much, resulting in not triggering an embedding update.

In my opinion, the ideal update strategy would be:

- Update the file's embeddings whenever the number of changed characters exceeds a fixed threshold (user-configurable).
- On top of the previous rule, limit the update interval (user-configurable).

What do you think?

Additionally, when searching for the nearest vector, it requires a linear traversal of all embeddings, with a time complexity of O(N), which might not be efficient enough when the knowledge base is large. If possible, employing the FAISS library or a vector database might be more effective for handling large-scale nearest neighbor search tasks.

**Comment by brianpetro** [comment]
@yan42685 thanks again for the analysis.

Smart Connections v2 will address this.

Your correct to assume the current implementation was designed to save tokens, which will be less of a concern as we move to a local embedding model in v2 (with option for continuing to use Ada/OpenAI ). 

As for Faiss, I don't think it would be compatible with the Obsidian plugin ecosystem (would require an additional software install, which I haven't ruled out for potential high value future features).

However, iirc Faiss is essentially a HNSW implementation in C. Basically just clustering and excluding groups of embeddings from search based on the cluster matches. While it's not top priority, it's definitely on my radar to implement something similar. Unfortunately, because the requirement of loading from disk to gain the performance improvements, and Obsidian plugins are forced to use a file-reading function through Obsidian instead of using FS directly, I'm not sure if we'd actually get the improved perceived performance gains. 

However, for performance, the local embedding model I plan on using creates significantly smaller vectors which would reduce the memory/cpu usage by >50% immediately for the same vault. Caching similar notes will also go a long way for improving performance.

Thanks for the analysis and insights. It's helpful to be considering all these different aspects as the v2 architecture gets clarified.

Overall, I think v2 will be night/day difference, at least from the code quality standpoint. V1 is effectively a first draft, done with zero planning. V2 will have a planned architecture that stems from many lessons I've learned building similar software over the past year.

Thanks again for the help!

🌴

**Comment by yan42685** [comment]
You're welcome :) I'm thrilled to get an early glimpse into Smart Connections v2 and am eagerly anticipating its release. It seems you've thought things through much more comprehensively than I have. I'm confident that v2 will be a version that truly dazzles. Thanks for your exceptional work!

**Comment by brianpetro** [comment]
@yan42685 😊

I hope to not disappoint!

V2 will be released to supporters first for beta testing.

If you're not a "supporter" already and the cost is a problem, send an email to supporters@smartconnections.app with a link to this GitHub issue so I can get you hooked up with a supporter key to get early beta access. Your insights are exactly the type of feedback I hope to receive during the v2 beta period.

🌴

**Comment by yan42685** [comment]
Thank you for your consideration! I've sent the email. I've hardly ever sent emails in English before and am not quite familiar with the etiquette, so please bear with me if it's not quite right, haha.

**Comment by brianpetro** [comment]
@yan42685 I didn't get the email. Let me know when you send again so I can check. And goodnight 💤

🌴

**Comment by yan42685** [comment]
OK, I have sent you emails from two different addresses to prevent my message sent via Gmail from being incorrectly marked as spam. If you happen to receive both, please prioritize the one from my Gmail. If you only receive the email from the address ending with @qq.com and can't find the one sent from Gmail in your spam folder, then I will continue to communicate with you using my QQ Email. Sorry for the inconvenience.

**Comment by yan42685** [comment]
I tested my email sending capability on mail-tester.com, and the results show that I can send emails normally in most cases. However, my IP has recently been added to a blacklist, which might be due to my use of a VPN.

![image](https://github.com/brianpetro/obsidian-smart-connections/assets/41834091/23100ad0-bb77-4b6e-a014-04e538cdaeba)

![image](https://github.com/brianpetro/obsidian-smart-connections/assets/41834091/befad4a7-6e5f-436d-be28-ce1d1a0dff70)

**Comment by brianpetro** [comment]
Got it @yan42685 !
