### ISSUE TITLE
FR: Generate embeddings on demand

### ISSUE THREAD

**Issue by Mearman** [brianpetro/obsidian-smart-connections#40]
I must confess to being an NLP novice and not fully understanding the concept of embeddings yet. But would it be possible to only trigger generation of embeddings on a per file basis when that file is opened?

Somewhat related to:
- https://github.com/brianpetro/obsidian-smart-connections/issues/33
- https://github.com/brianpetro/obsidian-smart-connections/issues/5#issuecomment-1366294366
- https://github.com/brianpetro/obsidian-smart-connections/issues/32
- https://github.com/brianpetro/obsidian-smart-connections/issues/31

**Comment by brianpetro** [comment]
Hi @Mearman and thanks for your willingness to contribute. 

Unfortunately, this is already being done. When the file is opened, if the metadata suggests the file has changed, then it re-embeds that file. 

It also makes sense to check for other file changes before generating the results to prevent returning stale results. 

Since there is a cost for every embedding, the best way to make the Embeddings usage more efficient is to save them as long as possible. This means using multiple ways to detect changes so that minor changes are ignored.

And so far, it seems the biggest problem in efficiency is when the Embeddings fail to be saved at all, which turns into all Embeddings being generated every time they need to be used. 

I should also mention that Embeddings are required for all files being included in the calculations. And since this app is designed to surface notes that you may have otherwise forgotten, it's important to embed all notes within relevant folders. 

I hope that helps your understanding about how the Embeddings system works.

**Comment by felipemeres** [comment]
There is another Obsidian plugin that facilitates note classification using GPT: https://github.com/HyeonseoNam/auto-classifier
It would be great to have a similar feature implemented in Smart Connections so as not to have to reembed all of the notes.

**Comment by brianpetro** [comment]
@felipemeres thanks for sharing
