### ISSUE TITLE
Implemented more granular result filtering in Smart View results

### ISSUE THREAD

**Issue by ksurya** [brianpetro/obsidian-smart-connections#401]
Sometimes I am working on a set of files. They have similar content. 

The smart connections ranks those at the top but I want to discover files that don't belong to this set. 

Is there a way to exclude a set of files by their file names or keyword in content at runtime?

**Comment by dvansoye** [comment]
Yeah. I have the same issue. I am a writer. I'm writing a series of articles on sleep for example. My Smart View is overwhelmed with all my other articles on sleep NOT the books, articles, etc. in my vault on sleep that I really want to see. This makes Smart Connections of limited value which is a shame. I excluded the folder that contains my articles and instead of excluding those notes from Smart View, it didn't show anything in Smart View. Is there a work around? Maybe, I could create a vault for my articles and paste the text in a temporary note to see the connections? Any help much appreciated.

**Comment by brianpetro** [comment]
@ksurya @dvansoye thanks for feedback

I've got at least a handful of ideas in the works that I think will each improve this. However, in the meantime, anything you can show/tell me about your specific cases will help me refine those strategies.

@dvansoye based on Smart View not showing anything, it might be worth checking if you accidentally excluded all notes?

As the software progresses, my objective is to move from the simple semantic similarity (current) to predicting which notes might be most useful (future). In addition to Smart Connections, this is also what I'm working on in another project of mine. 

🌴

**Comment by dvansoye** [comment]
Sure. I can help. 

As I mentioned, I'm a writer. I'm currently writing about sleep. There are 12 articles for the series. They are all in a particular folder (publikationen). 

The problem is that Smart View (on the right) is overwhelmed with the other articles that I've written about sleep. 

I have dozens of articles in my vault about moderate drinking, but they aren't surfaced. 

I want to exclude my articles from Smart View. Or, I want to temporarily exclude articles from Smart View. I mean, later, I might be writing in my diary, and I might want one of my articles to pop. But, when I'm writing articles, I don't want my other articles to pop. 

When I exclude the folder with my articles, it shows excluded in Smart View when I'm viewing an article. But, I don't want to turn off Smart View when viewing an article, I want to exclude my articles from being included in Smart View. 

It is all very confusing. But this means that I can't really use Smart Connections at all because my use case is to use it specifically for when I write. 

<img width="1331" alt="Screenshot 2024-01-11 081644c" src="https://github.com/brianpetro/obsidian-smart-connections/assets/14299260/cd71dc59-c504-4be6-ad9b-0bc0734884a1">

As I work around, I excluded my articles folder and copied the text of the article into a Temp note, but that didn't work either. Instead, when I opened Temp, Smart View showed my articles again (even though that folder was excluded). Yeah, excluded is unclear. Is it excluded from consideration or from view?

I hope that my screenshot above makes it clear. If you would like to chat further, let me know.

**Comment by dvansoye** [comment]
Good. I glad it helped. Always helps to see a screenshot. ☺

**Comment by brianpetro** [comment]
Note: might be related to #417

**Comment by brianpetro** [comment]
Note: similar to #423

**Comment by ksurya** [comment]
Thanks a lot @brianpetro for taking an interest on this :) 

This is such a great plugin!!

**Comment by brianpetro** [comment]
Smart Connections' New Smart View Features: Enhanced Filters & Re-Ranker Model: https://youtu.be/J2-uSbTD2RI

**Comment by dvansoye** [comment]
Fantastic Video, Brian. So helpful to see how it works. And congrats of making such a significant upgrade to SC. I appreciate the time it took to put it together!! 🥇
