### ISSUE TITLE
Get not response

### ISSUE THREAD

**Issue by rotello** [brianpetro/obsidian-smart-connections#50]
Sorry for the noobie question but i ve not been able to use this plugin (which could be SUPER interesting)

1. I ve created a NEW vault
2. added a long note and 50+ kindle
3. set up the API (and tested them) - i am on a PAID APi account
4. waited an hour
5. asked questions with "I"
6. got the ... dot
7 test the writing file and got an error: ENOENT - not such a file open .... /path/.smart-connections/embedding-test.json

I searched how to solve it with avail. 
can you please help?

**Comment by brianpetro** [comment]
@rotello thanks for following up about this. I'm sorry that your having this issue. 

Let me think about what might be causing this and I'll get back to you.

**Comment by rotello** [comment]
I ve installed in another vault (older) . Same error, but i was able to generate it using the "smart connection file icon".
I closed the "not working" vault & obsidian. opened it, and now the icon was there and i ve been able to generate the file.
i ve waitied almost 2 hours  and if I ask "hello" it does reply me. "Hello! How can I assist you today?"
but if i ask "do i like books?" "what can you tell from my books"? it s always 3 dots. i also manual saved it....  maybe i m missing something...

**Comment by rotello** [comment]
when i run "Open: View Smart Connections" everything seems fine
<img width="1076" alt="chatGPT-smart connections error - 1" src="https://user-images.githubusercontent.com/2255620/225863842-528be934-24f8-4e06-a004-64fa1b9fd99b.png">

now after a full night of "rest" the chat does reply me BUT it s totally useless (i m asking about storytelling, where there is a book called "storytelling")  - i think this ticket is solved and I am now into the issue #55 -


<img width="1156" alt="chatGPT-smart connections error - 2" src="https://user-images.githubusercontent.com/2255620/225864022-80d6d85c-1217-41cb-8e54-55f5f265be38.png">

![chatGPT-smart connections error - storytelling](https://user-images.githubusercontent.com/2255620/225864000-fa6e4b32-b1b2-4789-ba26-e75616ee8f5b.jpg)

**Comment by brianpetro** [comment]
@rotello thanks for the continued helpful feedback. 

In addition to your prompt, there are also prompts in the background that can be improved. 

The "always three dots" issue is possibly related the this issue is this comment https://github.com/brianpetro/obsidian-smart-connections/issues/51#issuecomment-1473742157

Overall, we're still at a barebones implementation of this feature. I think that there are likely some necessary presets that can be selected to "better fit" an individual's note taking style. 

Lots to do, but I love the helpful feedback. Please keep it coming and it will help me make this useful for everyone. Thank you!

**Comment by smartguy1196** [comment]
@rotello https://github.com/brianpetro/obsidian-smart-connections/discussions/72 may be helpful, if you aren't already using it.
