### ISSUE TITLE
Plugin (turned off) and says "cannot load plugin"

### ISSUE THREAD

**Issue by bbecausereasonss** [brianpetro/obsidian-smart-connections#521]
Just happened after turning Obsidian back on in the morning.

**Comment by brianpetro** [comment]
Is this on desktop or mobile?

I did recently disable mobile in v2.1 because of issues it was causing, and it wasn't ready anyway. 

If on desktop, there should be something in the logs. If you can screenshot that it would be helpful.

**Comment by brianpetro** [comment]
The developer console logs.

**Comment by bbecausereasonss** [comment]
2app.js:1 Plugin failure: smart-connections SyntaxError: Invalid or unexpected token
    at eval (<anonymous>)
    at app.js:1:2244346
    at e.<anonymous> (app.js:1:2244447)
    at app.js:1:237056
    at Object.next (app.js:1:237161)
    at a (app.js:1:235879)
(anonymous) @ app.js:1

**Comment by brianpetro** [comment]
Can you take screenshots? And also make sure the "debug at startup time" setting is toggled on in the community plugins tab.

**Comment by bbecausereasonss** [comment]
![image](https://github.com/brianpetro/obsidian-smart-connections/assets/20264016/e69f9f35-6c65-42dd-a9b2-035f35afd73a)

**Comment by brianpetro** [comment]
Thanks.

If you click the little triangle/arrow next to "Plugin" in the logs, it should expand the error log to see more details.

**Comment by bbecausereasonss** [comment]
![image](https://github.com/brianpetro/obsidian-smart-connections/assets/20264016/cc897ff7-7584-4eaa-a53f-a26763b4af34)

**Comment by brianpetro** [comment]
Unfortunately, nothing in that log was helpful.

Re-installing the plugin might fix it. A couple of notes about re-installing:

1) Before re-install, you can save your settings file located at `.obsidian/plugins/smart-connections/data.json`

2) If you're using `v2.1` currently, make sure to upgrade again to `v2.1` before starting any re-embedding processes. Otherwise, you will lose all the embeddings created in `v2.1`.

🌴

**Comment by bbecausereasonss** [comment]
Thanks. Will do. 

Had to re-embed anyway. Oh well. 

PS. In my embedding folder I keep getting a massive string of 'failed' files. And also keep getting "Dataview API not found" not sure if it's related to anything.

![image](https://github.com/brianpetro/obsidian-smart-connections/assets/20264016/e9045d5a-74db-4878-b5d3-8d0ae65f1569)

**Comment by bbecausereasonss** [comment]
![image](https://github.com/brianpetro/obsidian-smart-connections/assets/20264016/50cdf646-638d-423e-9ef7-f98485cf9b8a)

**Comment by brianpetro** [comment]
The errors there that are from Smart Connections have to do with context length. 

Maximizing use of the available context is still under development in `v2.1`. So, I'll be working on making those errors occur less frequently.

Based on the logs, the error appears after you've already received multiple responses from the AI. The issue is likely because the prior chat history isn't properly accounted for. So, if you start a new chat and ask the same "based on my notes" question, it should work.

But this is something I am already working on improving.

**Comment by blakejwc** [comment]
I just had this happen today. Errors in the console don't look useful either. I'm going to try reinstalling.

![image](https://github.com/brianpetro/obsidian-smart-connections/assets/979760/f8f2e829-c69b-47ff-a89d-c08ae3ba35c8)
