### ISSUE TITLE
Question about embedding models

### ISSUE THREAD

**Issue by ramarivera** [brianpetro/obsidian-smart-connections#546]
I can see we have quite a choice of models to choose from when it comes to embedding, thanks for that!

Some of those models are API based, and some of them are local.
Leaving aside the costs and processing time aspects, have you seen significant quality differences between e.g. using OpenAI Large and a local embedding model?

I don't mind using API models, as long as the quality offsets the costs, if that makes sense.

Thanks!

**Comment by brianpetro** [comment]
@ramarivera I use BGE-micro.

Benchmarks will say the X-model is better than the Y-model. But it really won't matter unless you have a significant number of very similar notes.

The context window size can impact the performance of note-level embeddings. For example, if a large portion is truncated due to the limit, it won't be a very accurate embedding. However, if you use block-level embeddings, most blocks (note excerpts) will likely fit in even the smallest context windows. 

🌴
