### ISSUE TITLE
Blank options window in Obsidian

### ISSUE THREAD

**Issue by clemensrettich** [brianpetro/obsidian-smart-connections#553]
When I click on Settings / Smart Connections under 'Community Plugins' at the bottom of the settings window, or click the settings gear after Community Plugins / Installed Plugins / Smart Connections I get a blank window. I have tried disabling and re-enabling Smart Connections and have shut down and restarted Obsidian. No change.

**Comment by Kenljs** [comment]
+1

**Comment by brianpetro** [comment]
Hi @clemensrettich 

Thanks for the report!

I just pushed a new update with some fixes, `v2.1.43`.

If it is still happening after that, please open the developer console to see if there are any errors in the logs.

Thanks for letting me know about this! @Kenljs 

🌴

**Comment by Kenljs** [comment]
Well, you're quick!
My settings console seems to be working now. Thank you!

**Comment by Hwenyi** [comment]
> Hi  Hello @clemensrettich
>
> Thanks for the report!
>
> I just pushed a new update with some fixes, `v2.1.43`.
>
If it is still happening after that, please open the developer console to see if there are any errors in the logs.
> 
Thanks for letting me know about this! @Kenljs
>
> 🌴

Thanks for the fix, but it seems still a bit unstable, the latest version still triggers the blank window. It happens when I disable other extensions and only keep this one, but it recovers after several refreshes or restart Obsidian, but it's almost usable now, thanks for your work ！

**Comment by brianpetro** [comment]
Hi @Hwenyi 

If it keeps happening, please open the developer console and take a screenshot so I can review any errors in the logs.

🌴

**Comment by clemensrettich** [comment]
We are back in operation! 
Thank you!
