### ISSUE TITLE
Smart Connections freezing and re-embedding frequently

### ISSUE THREAD

**Issue by MorganOnCode** [brianpetro/obsidian-smart-connections#583]
My Smart Connections instance has become unusable. 
Every time I try to use it, it either freezes or forces re-embedding, which then freezes my whole Obsidian app. 

Smart Connections used to be so good! It seems the latest updates have killed it for my machine. 
I'm on a Macbook Pro M2 Ultra chipset. 

When using chat, it fails frequently without any error warning - just doesn't function. 
Single line prompts in the chat sometimes work, but often don't. 
When I type a line break, it seems to fail more often. 

I'd like to understand if I'm doing anything wrong? 

These are my settings (it's presently frozen on this screen) 

<img width="975" alt="Screenshot 2024-05-05 at 10 42 12" src="https://github.com/brianpetro/obsidian-smart-connections/assets/87934408/e87e0eb8-8803-4c66-ba18-df9f75fc235a">

**Comment by AdalaceV2** [comment]
I seem to also be suffering from this same issue. Freezing on my end too.

**Comment by brianpetro** [comment]
Hi @AdalaceV2 & @MorganOnCode 

Thanks for letting me know about this.

While the computer hardware running Obsidian may be overall sufficient, the underlying software Obsidian uses (electron) arbitrarily limits memory usage. That's why running almost any model within Obsidian tends to grind things to a halt.

You can improve this immediately by getting the Smart Connect software. Smart Connect uses the same internals to offload the embedding processing from the Obsidian app. To do this, install and open Smart Connect, then click "Connect to Smart Connect," as seen in the screenshot above, to begin using it for your embeddings. 

> Every time I try to use it, it either freezes or forces re-embedding, which then freezes my whole Obsidian app.

See https://github.com/brianpetro/obsidian-smart-connections/issues/578#issuecomment-2096835694 for a couple important notes for preventing re-embedding.

> Smart Connections used to be so good! It seems the latest updates have killed it for my machine.

This is most likely due to the introduction of local embeddings. If you switch back to OpenAI embeddings, performance should be equivalent to `v1.x.x` while still having the many new and improved features added since `v1`.

> When using chat, it fails frequently without any error warning - just doesn't function.

Is this during the embedding processing? 

> Single line prompts in the chat sometimes work, but often don't.

Can you send me a screenshot of the developer console logs when this happens so I can take a look?

> When I type a line break, it seems to fail more often.

Is this in reference to the chat input? Or on a note during the embedding processing? Considering the above, it would make sense if it is the latter since a new line in a note will cause re-rendering, which could cause the application to exceed that arbitrary memory limit.

Thanks for your help in getting to the bottom of these issues
🌴

**Comment by brianpetro** [comment]
Hey @AdalaceV2 

Make sure you update to the latest version, just made a few bugfixes now available in `2.1.57`.

Then open the dev console using `View > Toggle Developer Tools` to see the logs.

Thanks for your help
🌴

**Comment by AdalaceV2** [comment]
Ok I've narrowed it down.

It is triggered whenever I try to access the search (through the magnifier icon) after moving a file to a different folder.

The program goes into an infinite loop of this message:
![image](https://github.com/brianpetro/obsidian-smart-connections/assets/87100382/8bb42ca8-f7e3-4c1c-85e9-55a8b5dbfb0a)

This happens here:
![image](https://github.com/brianpetro/obsidian-smart-connections/assets/87100382/46799825-233f-4c54-8289-6a0948fcb27d)

Because of this error:
![image](https://github.com/brianpetro/obsidian-smart-connections/assets/87100382/0fc12384-db44-430e-bc59-07143c649702)

**Comment by MorganOnCode** [comment]
<img width="798" alt="image" src="https://github.com/brianpetro/obsidian-smart-connections/assets/87934408/f96a4fc8-2847-4aea-8a0f-1019a5b6a4fc">

This doesn't seem that useful to me. 
I uninstalled Smart Connections for a bit because it was making Obsidian unusable. 
I've reinstalled to try to fix. 

@brianpetro - How can I help navigate the dev console and give you useful data?

**Comment by MorganOnCode** [comment]
Hey @brianpetro, 

<img width="829" alt="image" src="https://github.com/brianpetro/obsidian-smart-connections/assets/87934408/a43d7c9a-6c50-4c1c-9edc-3d6ac4a63786">

> See https://github.com/brianpetro/obsidian-smart-connections/issues/578#issuecomment-2096835694 for a couple important notes for preventing re-embedding.

I've selected the "Embedding file per note (EXPERIMENTAL)" setting and it seemed to give me these red errors in the console. 
I also set all the models to OpenAI in input a fresh API key (which was validated and works). 
Sadly, Obsidian immediately crashed and I've had to force quit it again. 

> Is this in reference to the chat input? Or on a note during the embedding processing? Considering the above, it would make sense if it is the latter since a new line in a note will cause re-rendering, which could cause the application to exceed that arbitrary memory limit.

Yes, when I was able to chat with it, a single line input would get a response, but a multi line (with a line break return) input would get no response. 

When I get it working again, I'll paste the logs 

I'd love for Smart Connections to work again

**Comment by MorganOnCode** [comment]
@brianpetro - I got SC setup, the API key is entered and it seemed to finish embedding. But: 

<img width="1366" alt="image" src="https://github.com/brianpetro/obsidian-smart-connections/assets/87934408/b8cc5aa3-2430-44e5-8bff-6120de901030">

When I ask it basic questions, it says it doesn't have access to my notes.

**Comment by brianpetro** [comment]
Hey @MorganOnCode 

Thanks for the screenshots! While they may look like gibberish, they do help.

If you don't mind, turning on the "debug at startup time" in the community settings tab will make the logs more helpful (it gives me accurate file names and line numbers for inspecting the code).

Based on the logs, I can see that it looks up your notes. However, it seems that the lookup is failing to return any results.

This is likely because either the embeddings don't exist or the embeddings failed to load.

One way to confirm this is to see if the Smart View is working. If the Smart View is not working, then the lookup in the chat won't work either.

Thanks for your help and patience while we figure this one out
🌴

**Comment by bbecausereasonss** [comment]
For the record, since the new releases I'm having the issue of being asked to rebuild embedding every time I switch between PC/OSX again. This stopped happening before after I did the individual embeddings, and synched to a seperate folder, but now it's back and Im unsure why.

**Comment by brianpetro** [comment]
Hey @bbecausereasonss 

Are you syncing the embeddings folder? 

I recommend _not_ syncing the folder. Each device will have to "catch up" with any changes made on the other devices, but this processing time should be negligible unless you make major changes.

Are you on the v2.2 early release? 

On v2.2, I've been switching back and forth between OSX and Windows and haven't noticed any unnecessary re-embeddings.

Can you make the issue happen on demand, i.e., by opening on one platform, closing, then opening on the other platform and observing the issue?

Thanks for the update
🌴
