### ISSUE TITLE
Using "connect to smart connect" for local embeddings restarts the plugin settings

### ISSUE THREAD

**Issue by ramarivera** [brianpetro/obsidian-smart-connections#587]
![image](https://github.com/brianpetro/obsidian-smart-connections/assets/7547875/b03b9cbe-b3e0-484b-b642-147f3bb2b225)

When clicking there, the plugin settings goes black, I get two notices about there being a new version of the app, and the embeddings restart

**Comment by brianpetro** [comment]
> When clicking there, the plugin settings goes black

This is expected. It's because the plugin is being restarted, and I haven't implemented a re-render-after-restart method for the settings.

The embeddings will continue to restart until they make it all the way through to finishing the embedding process. Embedding progress is saved every 500 embeddings or when you hit "Pause".

🌴
