### ISSUE TITLE
[improvement] Saving chat

### ISSUE THREAD

**Issue by rotello** [brianpetro/obsidian-smart-connections#59]
it would be nice to able to save chat into a new note

**Comment by brianpetro** [comment]
Yes! I do plan on saving chat history. But I planned on saving it in the background instead of as a note. This way, chats could be reloaded into the chat window.

I would like to know more about how you want them saved as notes.

Is there anything specific about how you would like to be able to save it to a note? 

Do you have any specific thoughts on the formatting if it were to be saved to a note?

Do you think a "Copy to clipboard" button would suffice?

Thanks for your continued contributions!
Brian🌴

**Comment by rotello** [comment]
I am not technical at all so I don't know how what I am gonna say is difficult / easy.

YES - A copy to clipboard would suffice for sure (copy, CMD+N, paste is super fast)

the formatting should be easy enough to edit (so simple text, with a break line between question and reply - exactly as it s now if you select all, copy paste)

The "save" as a note would be great coz i can create a folder where all the notes go, they are searchable / future proofed, i can delete, edit, move the part i need and generally doing some kind of maintenance. -
 but i understand that in this way they could no be loaded into the chat window... with ChatGPT 4 how much is important the previous content for getting better reply? on version 3.5 not so much 
 and the second issue is that you need to create a "negative folder" for not indexing the AI-generated text

maybe you can save in the background AND have manually to move into notes. (a button near the + or something)

at the moment it s frustrating to have 10 mins chat and losing it.

**Comment by sam1am** [comment]
It does seem that saving it as a note would add a memory of the conversation you could refer to later, right? That would be cool.

**Comment by brianpetro** [comment]
@rotello a copy button has been added in the `v1.4.0` update.

Also, chat history is in the works @sam1am 

The `1.4` update includes a backend update that enables the chat history. The UI has yet to be implemented. Though

**Comment by smartguy1196** [comment]
related: #81

**Comment by brianpetro** [comment]
Chat history added in `v1.4.6`

**Comment by SkyStreet** [comment]
Thx for updating! Well, for me now the question becomes where the history is saved in vault? How can I delete it? And I could not find the copy button while there are 4 buttons up there including 'smartview', 'save', 'history' and 'new chat'.

**Comment by brianpetro** [comment]
@SkyStreet look for the history in the `.smart-connections/chats` folder. It's hidden, so you'll have to use your normal file explorer to find it. Deleting from the UI will come soon. 

The copy a message button is in the bottom right corner of messages from the AI. Is that what you're looking for?

**Comment by SkyStreet** [comment]
@brianpetro perfectly solved. thx.

**Comment by avataraustin** [comment]
If i'm not mistaken currently I need to hit the copy button in the chat for each piece of the dialogue between me and chatgpt in the chat window if I want to copy it into a note to work with in Obsidian.  I agree with OP that it could be very helpful to have a button that just grabs the whole chat into a new obsidian note. I don't think it needs to be too fancy, its just a rather cumbersome process right now. It could be as simple as just having a linespace between each question and response.  
It could also simply be helpful if there was a  button to copy the whole chat (rather than copying each piece of the dialogue) and then the user could just past it into a new note.  
I hope I am not missing this feature if it already exists somewhere, but I do not see it when checking.

**Comment by LinuxIsCool** [comment]
I believe the app should have a feature "Save chat as note" That dumps the whole chat to a new note in a specified folder from settings.

**Comment by brianpetro** [comment]
@LinuxIsCool yes!

In `v2.1` the whole chat history will be in markdown format, with one note per thread 😊

🌴

**Comment by brianpetro** [comment]
And version 2.2 implements canvas format for saving Smart Chats 🌴

![Screenshot 2024-06-27 104407](https://github.com/brianpetro/obsidian-smart-connections/assets/1886014/4386cbdc-9d29-418b-aa8d-a4ce8139302b)

**Comment by brianpetro** [comment]
Recorded response https://www.youtube.com/watch?v=6l1R5zBqPP0

**Comment by Ar9av** [comment]
I ran into the same general problem often enough that I ended up building a separate markdown-first workflow for it: https://github.com/Ar9av/obsidian-wiki

The useful part is having a reliable path from AI conversation -> markdown in Obsidian -> later query/update, instead of manual copy/paste of fragments. Your issue describes that pain pretty directly.

Sharing in case the capture flow or note structure is useful as a reference.
