### ISSUE TITLE
FR toggle collapse-all smart connections in view

### ISSUE THREAD

**Issue by abdcef** [brianpetro/obsidian-smart-connections#62]
This is a great feature! Is it possible to have files in the sidebar collapsed by default? Otherwise, it takes a lot of sidebar real estate.

![CleanShot 2023-03-19 at 21 21 30](https://user-images.githubusercontent.com/56148250/226177902-259514f0-dbe7-4f73-9591-2a86285b6944.png)

Also, arrange in descending order of the percent match:
![CleanShot 2023-03-19 at 21 23 34](https://user-images.githubusercontent.com/56148250/226178006-64dbc804-ebbf-4e50-bf37-1853ebd44182.png)

I am pondering why does AI allocate a higher percentage to daily notes of other days than embedded atomic notes from the same date? The embedded atomic notes have the title [[YYYYMMDDttmm-abcd]] and contain [[YYYY-MM-DD]] in their content.

**Comment by brianpetro** [comment]
@abdcef yes, this is a feature I've been wanting to add.

And the descending order is another shortlisted feature. The lack of ordering is actually because it's currently "nesting" blocks under their respective files. But I plan to revert that to a strict "sort by descending similarity."

> I am pondering why does AI allocate a higher percentage to daily notes of other days than embedded atomic notes from the same date? The embedded atomic notes have the title [[YYYYMMDDttmm-abcd]] and contain [[YYYY-MM-DD]] in their content.

It's to tough to say without seeing the full content of the embed input. But sometimes the "surprising" connections can be the most useful. I also still need to do some work to make the plugin work better with date-based & zettelkasten note systems, so it could just be some fluke around that lack of integration at this point.

Thanks for adding this feature request, I hope to get to it soon! 
Brian 🌴

**Comment by brianpetro** [comment]
@abdcef I almost forgot, there is a setting named `expanded_view` which you can use. Toggle the setting off, and the notes in the Smart COnnections view will be collapsed by default.

**Comment by brianpetro** [comment]
@abdcef I updated that the results in the view are now un-nested by default. This can be reverted using the `group_nearest_by_file` toggle in the display settings. This update displays the results in descending order by similarity percent unless you revert to the previous rendering using the group-by-file option.

Thanks for your help with this.

Brian 🌴

**Comment by abdcef** [comment]
Wow! I was just wondering what the new update was about. I must admire the responsiveness, way to go!!
