### ISSUE TITLE
FR Enabling Smart Chat to Understand Task Prioritization

### ISSUE THREAD

**Issue by abdcef** [brianpetro/obsidian-smart-connections#70]
I manage tasks in Obsidian through the plugin. It is a bit of a process.
Can AI help in creating easier natural language chat-based task workflows?
Example: Which tasks are due tomorrow? What am I supposed to do tomorrow?
I tried but AI just keeps thinking and thinking and thinking...

**Comment by brianpetro** [comment]
> I manage tasks in Obsidian through the plugin. It is a bit of a process.

Me too, I know what you mean.

> Can AI help in creating easier natural language chat-based task workflows?
> Example: Which tasks are due tomorrow? What am I supposed to do tomorrow?

Short answer, yes. However, I'm still putting the pieces together.

A lot of it depends on how each individual labels their tasks, "due tomorrow," "high-priority," etc.

If the tasks are consistently labelled and in a small number of notes, it might be possible to achieve this already with some careful prompting.

However, if you're like me, there are high-value tasks, sometimes single lines, scattered across many notes. So that's a bit of an aggregation challenge.

I think automating the delivery of "what's due" might also be pretty important, because otherwise having to ask specific questions could begin to add up to as much friction as browsing the relevant notes/scopes.

> I tried but AI just keeps thinking and thinking and thinking...

This sounds like it could be a bug. If a response doesn't appear, check the console log for errors and let me know if you see any. 

@abdcef thanks for starting the discussion about this!

**Comment by abdcef** [comment]
It’s heartening to note that I’m not the lone wolf struggling with tasks, lol
I understand that the task related syntax can be loose and therefore difficult for a prompt to accurately interpret. Another approach can be to suggest a task management workflow enabled by AI. I imagine that will be less complicated than the options currently available. I use atomic notes, so my tasks are scattered all over. But I wouldn’t mind a simpler set of terms to adhere to than using dialog boxes to write complex set of fields that can be queried using a programming language or shown as dataview tables 🙄

**Comment by brianpetro** [comment]
Dataview queries are how I currently aggregate my tasks. Is that what you're doing, too?

How are you indicating priority?

Given the context window limitation of GPT models, my best thought so far is providing the results of those dataview queries to the AI as context.

Also, what do you think the AI task management workflow might look like?

**Comment by brianpetro** [comment]
@abhuva version `1.4.13` sets the relevant temperature to 0.

**Comment by abhuva** [comment]
> @abhuva version `1.4.13` sets the relevant temperature to 0.

I see this as a temporary fix, there are certainly use cases where one would benefit from a higher temperature.
For example:
"based on my notes, give me some possible research topics"
"for my project xy, help me find possible titles and describtions"

These certainly benefit from some randomness.
I still think it would be good to have this variable exposed either in settings or in frontmatter.

**Comment by brianpetro** [comment]
Closing this because the most recent discussion deviates from the issue title. If any of these topics are still an issue, please either re-open or create a new and more-specific issue regarding the feature you would like to see 🌴

**Comment by brianpetro** [comment]
Recorded response https://youtu.be/5x1EhQiBcxo
