### ISSUE TITLE
Smart connections tab stays blank.

### ISSUE THREAD

**Issue by Ruboks-Cube** [brianpetro/obsidian-smart-connections#735]
Here is an image of my situation, the smart connections tab is open but nothing is happening. This started happening pretty recently. I'm not sure what it means in the dev tools but I thought it would be useful to send that too. IDK any other information. My settings are default settings I don't use the chatbox much either.
![image_2024-08-23_092602263](https://github.com/user-attachments/assets/2c7a1d86-57bf-423c-86fc-7e6f318c3110)

Edit: IT works fine after doing the refresh. However, I did this yesterday too and it worked but today it started not working as well. 

Edit: After a bit it didn't work anymore. If it does work it gets stuck on one note and I can't do "refresh" with ctrl+p or clicking out of the note does not work. 

![image](https://github.com/user-attachments/assets/5db89a90-acbf-428f-9c30-98daa2a60c58)

**Comment by jowitte** [comment]
Hi @brianpetro . I have a quite similar issue: Since some time Smart Connections causes Obsidian to freeze for some seconds each time I switch notes while I get a Smart Connections notification and the console log shows something like this:

![Screenshot by Dropbox Capture](https://github.com/user-attachments/assets/b80058a6-acbf-4efa-8291-7dceff1d4cda)

Some related notes section sometimes doesn't show anything:

![Screenshot by Dropbox Capture](https://github.com/user-attachments/assets/d13245e1-3016-481f-be1e-2e329100a23f)

Or it shows the related notes of the previously active file. 

This happens in the stable version as well as in the newest 2.2

**Comment by Dnarts** [comment]
Please assist; the refresh and restart buttons are not working. I attempted to reinstall, but it would not function.

![image](https://github.com/user-attachments/assets/8f84a6a8-6bbb-4829-855a-34a5585a54c6)
​

**Comment by bbecausereasonss** [comment]
Yes been having this issue a lot lately and having to completely re-embed my entire folder; mind you now it won't even re-embed, it's pausing/freezing mid-way through with OpenAI-Small.

**Comment by HLuisPP** [comment]
I'm having the same issue with Smart Connections version 2.2.66. It doesn't load the smart connections and it freezes Obisidian momentarily.

SYSTEM INFO:
	Obsidian version: v1.6.7
	Installer version: v1.4.13
	Operating system: Windows 10 Pro for Workstations 10.0.22631
	Login status: logged in
	Catalyst license: supporter
	Insider build toggle: off
	Live preview: on
	Base theme: dark
	Community theme: Minimal v7.7.18
	Snippets enabled: 3
	Restricted mode: off	
		55: Smart Connections v2.2.66
![smartconnection_2_2_66_issues_loading_1](https://github.com/user-attachments/assets/76e10e82-6c72-40f0-8146-8575716e42b1)
![smartconnection_2_2_66_issues_loading_2](https://github.com/user-attachments/assets/41ef75ad-76d3-45be-8c9c-4fa500608e90)

**Comment by Dnarts** [comment]
I solved this on the topic below:
https://github.com/brianpetro/obsidian-smart-connections/discussions/768#discussioncomment-10608834

**Comment by christianngarcia** [comment]
Thanks for sharing a solution. 😊
