### ISSUE TITLE
Excalidraw: Failed File Loop

### ISSUE THREAD

**Issue by yannlk** [brianpetro/obsidian-smart-connections#75]
Hi, thanks so much for the plugin. I have this one issue I found. I will get notifications about failed embeddings recurring reasonably often because of my excalidraw file in my vault. It would be so nice if when excalidraw was detected, (even though its technically a markdown file), smart connections skipped it so it would have a loop of failed embeds. 
<img width="573" alt="image" src="https://user-images.githubusercontent.com/104253173/226703747-8439c5ad-6bba-4cd6-8b61-05e6d7e497c7.png">

**Comment by smartguy1196** [comment]
It's unlikely that Excalidraw is causing problems. It is more likely that you've hit an OpenAI rate limit

**Comment by smartguy1196** [comment]
see:
- https://github.com/brianpetro/obsidian-smart-connections/discussions/66
- https://github.com/brianpetro/obsidian-smart-connections/discussions/67
- https://github.com/brianpetro/obsidian-smart-connections/discussions/72

**Comment by smartguy1196** [comment]
Additionally, as most Excalidraw drawing files won't have useful information for smart-connections, I recommend adding the Excalidraw folder to the excluded folders for smart-connections.

Not required, but if your Excalidraw .md files don't have useful text in them, you are probably just burning up your OpenAI key (which will cost you money)

**Comment by brianpetro** [comment]
@yannlk is this happening only when you open the excalidraw file?

If excalidraw is in the filename, there is a check that semi-excludes them by only embedding the file name and path.

However, the excalidraw files are somewhat easy to parse, and I do have an update in the works that will eventually support them as a file type, since I regularly use excalidraw, too (great plugin). 

Similarly, I would also like to support canvases. Those will likely be first since they tend to have more useable text in the file.

And thanks @smartguy1196 for helping trying to clear this one up.

**Comment by smartguy1196** [comment]
> If excalidraw is in the filename...

> However, the excalidraw files are somewhat easy to parse, and I do have an update in the works that will eventually support them as a file type, since I regularly use excalidraw, too (great plugin). 

I wouldn't check for excalidraw files by filename, as Excalidraw has settings for changing the default (I use this setting quite often, because I personally don't like the default).

I would check by file content. I believe Excalidraw files have a pretty unique code block type embedded in them that you could look for.

**Comment by brianpetro** [comment]
Created issue in JS Brains for creating Excalidraw adapter https://github.com/brianpetro/jsbrains/issues/5

**Comment by brianpetro** [comment]
Response video https://www.youtube.com/watch?v=2Qn2YmmqJfY
