### ISSUE TITLE
Issue Embedding using OpenAI API Key after latest update v2.1.96

### ISSUE THREAD

**Issue by Nesador95** [brianpetro/obsidian-smart-connections#751]
I'm using my OpenAI API key for embeddings and I still have issues embedding similar to this  #750. I'm getting this messages which I didn't use to get before:
"Rate limit reached for text-embedding-3-large in organization <redacted> on requests per min (RPM): Limit 3, Used 3, Requested 1. Please try again in 20s. Visit https://platform.openai.com/account/rate-limits to learn more. You can increase your rate limit by adding a payment method to your account at https://platform.openai.com/account/billing."
I checked and I have plenty of funds for the embedding, that shouldn't be a problem. maybe it's the rate of request going too fast?
![image](https://github.com/user-attachments/assets/be0f9630-0933-4488-b8b7-a831378c8ccf)

**Comment by brianpetro** [comment]
Thanks for letting me know. And thanks for sharing the screenshot. 

It looks like there's a bug causing the batch size to be reduced from 50 to 10. Once I fix this bug it should fix the issue 🌴

**Comment by brianpetro** [comment]
This should now be fixed in `v2.1.97` 🌴

**Comment by Nesador95** [comment]
Thank you for such a quick response! your work is amazing!

**Comment by Nesador95** [comment]
Just updated to the new version, but although the embeddings progress now goes up to 150, the issue persists and it gets stuck there.
![image](https://github.com/user-attachments/assets/9e7e9ab7-77ca-4f43-ab6a-1206b9f387bc)
😞

**Comment by bbecausereasonss** [comment]
Came here to post, after the latest update I had to re-embed everything and it keeps freezing. I'm trying to use large model openAi. and It stops in the middle everytime.

**Comment by bbecausereasonss** [comment]
![image](https://github.com/user-attachments/assets/e703551a-30dd-430c-9da3-763a93f71563)

**Comment by bbecausereasonss** [comment]
@brianpetro My error.

**Comment by bbecausereasonss** [comment]
More errors. Cannot make or read embeddings at all anymore.

![image](https://github.com/user-attachments/assets/ca6812ee-61a6-4136-8130-97c67ef490d4)

**Comment by brianpetro** [comment]
@bbecausereasonss the 520 error looks like it could be coming from an OpenAI server issue (or, more likely cloud flare issue, which is why the built-in error handler isn't working).

The openai status page says everything is working, though it typically has been an unreliable indicator so I wouldn't go as far as saying that's accurate. I wouldn't be surprised if the issue simply disappeared at some point because of this.

@Nesador95 the OpenAI embedding adapter implements exponential backoff with is standard/best-practice for handling rate limit issues. It's interesting that it's not a sufficient solution in this case.

I did rewrite the Smart Embed Model component, and that was shipped in the last few versions, so it is very likely that something changed to cause this.

I also tested generating >10K embeddings just now with multiple OpenAI models and didn't run into either issue.

My thought is to double-check your OpenAI accounts to ensure there is sufficient prepaid credit or that you've completed whatever other hoops OpenAI wants you to jump through to use their API.

Besides that, let me know if anything else changes. I did review the code while those embeddings were processing and I didn't see anything that jumped out. So any additional clues would be helpful.

And thanks to both of you for the helpful screenshots. Even though the issue isn't solved, they were helpful in clarifying where the problem is occurring. 🤞 we'll get this one fixed soon.

🌴

**Comment by bbecausereasonss** [comment]
Seriously confused. Was working before this, but now won't embed... I even tried to re-install and totally nuke everything.

![image](https://github.com/user-attachments/assets/5f7e6f6c-2374-412b-8fa1-c1c855b00ea2)

**Comment by brianpetro** [comment]
For anyone where the embeddings were working pre-`v2.1.96`, see https://github.com/brianpetro/obsidian-smart-connections/issues/749#issuecomment-2324472086 🌴

**Comment by Nesador95** [comment]
> @bbecausereasonss the 520 error looks like it could be coming from an OpenAI server issue (or possibly cloud flare issue, which is why the built-in error handler isn't working).
> 
> The openai status page says everything is working, though it typically has been an unreliable indicator so I wouldn't go as far as saying that's accurate. I wouldn't be surprised if the issue simply disappeared at some point because of this.
> 
> @Nesador95 the OpenAI embedding adapter implements exponential backoff with is standard/best-practice for handling rate limit issues. It's interesting that it's not a sufficient solution in this case.
> 
> I did rewrite the Smart Embed Model component, and that was shipped in the last few versions, so it is very likely that something changed to cause this.
> 
> I also tested generating >10K embeddings just now with multiple OpenAI models and didn't run into either issue.
> 
> My thought is to double-check your OpenAI accounts to ensure there is sufficient prepaid credit or that you've completed whatever other hoops OpenAI wants you to jump through to use their API.
> 
> Besides that, let me know if anything else changes. I did review the code while those embeddings were processing and I didn't see anything that jumped out. So any additional clues would be helpful.
> 
> And thanks to both of you for the helpful screenshots. Even though the issue isn't solved, they were helpful in clarifying where the problem is occurring. 🤞 we'll get this one fixed soon.
> 
> 🌴

I have double checked my OpenAI account and I have enough funds for what I'm doing, also have enough notice in advance before those funds are depleted.  I was successful on using their embedding system before 2.1.96 update (as in literally was using Obsidian, go the notice of new update and updated), so I'm pretty sure that my OpenAI API connection is not the issue. It might be that your Organization limit is at a much higher Tier than mine and that's why the requests are going through, I don't make nearly enough request to even put me up to usage tier 1 so that might be why you can do it but I can't?
I can't see any other console errors different than what has been posted. At the very least it looks like you can't do batches more than 200 requests a day at the most basic level of usage, and you can't exceed 3 requests a minute, perhaps one can choose which limit to use or that information can be gathered from the API? (not super familiar with how it works) but that seems to be the issue in my oppinion 
![image](https://github.com/user-attachments/assets/93c79f47-3be1-4ef4-b42b-ca6b0c63931f)

P.S. I tried the Toggle from your latest comment, but it doesn't affect the API part, it did help with the local embeddings system, though, so there's progress!

**Comment by brianpetro** [comment]
@Nesador95 I am happy to hear we've at least made progress with the local embeddings 😊

Regarding OpenAI, you may want to reach out to them about your account because this is what I'm seeing for free-level (lowest tier) rate limits:
![Screenshot 2024-09-02 at 8 59 41 AM](https://github.com/user-attachments/assets/778ff769-7de2-4dd9-a48b-baa86d52c5cc)

Tier 1 (minimum $5 deposited) completely removes the daily limit (though 200 RPD should be sufficient as the requests are made in batches of 50).

source: https://platform.openai.com/docs/guides/rate-limits/free-tier-rate-limits

🌴

**Comment by Nesador95** [comment]
Yeah I'm wondering about that, it seems like their documentation hasn't been updated to what's shown in my organization page.
![image](https://github.com/user-attachments/assets/700348a7-af6a-4083-a2d6-f1195e7e340b)
there it says that I have to "spend" the $5 in usage not just pre-pay them.
Still though, my usage of the text-embedding goes like this
![image](https://github.com/user-attachments/assets/4974b094-6213-4c54-8d74-d95ac5e00db4)
so that's what I'm hitting against.  I wonder if it's a regional variation on service.

**Comment by Nesador95** [comment]
This is what happens when I monitor my OpenAI account when I try to run embeddings with the plugin
![image](https://github.com/user-attachments/assets/ad448d7b-842f-4ba2-9f3b-50f9bf0b9b1e)
So there are too many requests at a time confirmed, maybe a bug in a loop?

**Comment by Nesador95** [comment]
The number of  rpm's was updated, it was an issue on their end.

**Comment by brianpetro** [comment]
@Nesador95 thanks for the follow up 🌴
