### ISSUE TITLE
two embedding processes from different versions happening at once

### ISSUE THREAD

**Issue by bbecausereasonss** [brianpetro/obsidian-smart-connections#755]
Since last 2x updates, I've been unable to create-embedings or use the app. It's either constantly freezing, stopping mid-way throwing different errors or just doing odd things. There are now far more prompts I don't recognize but also it seems to think both versions of the plugin are installed and doing 2x embedding streams for a previous and new version. All kinds of weird things happening. I haven't been able to use/create embeddings at all.

![image](https://github.com/user-attachments/assets/b160fd3a-8843-45a7-8387-5242727cc496)

**Comment by brianpetro** [comment]
@bbecausereasonss I sincerely appreciate your help in bringing issues to my attention, but I think it's important that I clear some things up:

1) The title of the GitHub issue should be specific to the problem you are experiencing. Otherwise, 99% of issues would have the same title.

2) If the issues you are experiencing have all started happening around the same time, then all relevant information should be contained in the same issue. Having to piece together different symptoms from multiple threads is not helping me get things back in order any faster.

---
Re: issue: the two embedding processes from different versions happening at once

This should be a relatively rare occurrence but can be fixed by restarting Obsidian. Pausing the process before restarting will save progress. However, the progress on the earlier version likely cannot be saved as its associated plugin instance should have been unloaded 🌴

**Comment by bbecausereasonss** [comment]
Got it, apologies on the mess.

**Comment by algieg** [comment]
I have the same issue. Everything seemed to be working fine in 2.1.96. Then I was away for a while and today quickly installed 2.1.97 - 2.1.99 in quick succession. As a result, I'm stuck with the "Loading Smart Connections..." screen even though the embedding pop ups both for the local BGE model and for the text-small OpenAI model completed successfully (I forced reset after resetting embeddings and resetting sources failed).

![image](https://github.com/user-attachments/assets/40361442-2e7c-421f-9340-bda6d5fe3830)


Any idea on what could work?

**Comment by brianpetro** [comment]
@algieg an Obsidian restart might help. Also, screenshot any console errors when the "Loading Smart Connections..." isn't progressing as expected. This will help me better see any errors that might be preventing the loading process from completing 🌴

**Comment by algieg** [comment]
Thanks for your quick reply and readiness to help! Here are the logs on a freshly restarted Obsidian (before restart I forced reset and waited for embeddings to be complete):

![image](https://github.com/user-attachments/assets/032742d5-1cd2-4a38-84cc-3b4d464b5d8b)
![image](https://github.com/user-attachments/assets/d3fd1f92-c5eb-47bb-9311-688fb022fd85)

**Comment by brianpetro** [comment]
@algieg you may want to try https://github.com/brianpetro/obsidian-smart-connections/issues/749#issuecomment-2324472086 🌴

**Comment by algieg** [comment]
Apologies, I should have stated I did find your comment there and have applied it already:
![image](https://github.com/user-attachments/assets/43206c31-8bbd-4fbb-a488-ba0045498bdf)

**Comment by bbecausereasonss** [comment]
So, re-trying Open-Ai embedding with Smart Connect. It seemed to Ebmed the full vault (notes), but seems stuck again at making Smart Connections;

![image](https://github.com/user-attachments/assets/70e4647b-278a-49d6-b939-374530cd6db2)

**Comment by brianpetro** [comment]
@algieg gotcha. 

In that case, make sure you also see this https://github.com/brianpetro/obsidian-smart-connections/issues/756#issuecomment-2324763620

**Comment by bbecausereasonss** [comment]
As per comment in another thread rolling back to 2.1.95 (fixed my issues) the app is now performing way faster, not freezing my obsidian and is creating/reading embeddings for notes/blocks with ease.

**Comment by brianpetro** [comment]
Ok, or try with a small test vault 🌴
