### ISSUE TITLE
BUG: Unable to type in chat

### ISSUE THREAD

**Issue by maylward1** [brianpetro/obsidian-smart-connections#90]
Using obsidian on Mac, with the following plugins: advanced tables, auto link title, dataview,linter, minimal theme, Omni search, text extractor. I’m unable to click into or type in the dialog box in the chat window.

**Comment by brianpetro** [comment]
@maylward1 thanks for the report. I don't know what's causing this. I tested with the minimal theme, so that isn't it.

If you could, may try disabling those plugins to see if anything changes. If there is any sort of interference, I can better debug from there.

Thanks again for your help solving this!

**Comment by smartguy1196** [comment]
Additionally, could you follow the instructions from https://github.com/brianpetro/obsidian-smart-connections/discussions/72 and post screenshots here?

**Comment by maylward1** [comment]
I figured it out— the color scheme (mac os) I was using in Minimal made it so the text entry box next to the “send” button was basically invisible. I can click on it (now that I know it’s there) and it becomes highlighted, but without that it’s just white space.

**Comment by brianpetro** [comment]
@maylward1 wow, I missed that when I looked the first time. After you said that, it was obvious. Fixed in version `1.4.8`
